### ISSUE TITLE
AutoReject deprecated? 

### ISSUE THREAD

**Issue by so-phi** [autoreject/autoreject#107]
I have just started using autoreject, so sorry if this is obvious. But I could not find a hint at my problem when looking at the other issues.

When I try to  use AutoReject, as explained in the Quickstart guide:
```
 from autoreject import AutoReject
    ar = AutoReject()
```
I get an "cannot import name 'AutoReject' " error. I could however import GlobalAutoReject or LocalAutoreject. 

Has AutoReject been replaced by these functions or am using a wrong way of importing the class?

**Comment by so-phi** [comment]
Hi @jasmainak, autoreject was already on version 0.1 . I have reinstalled it using the latest version on pypi but the error is the same.  Here is list of the other packages+versions I'm using in that environment:

autoreject==0.1
certifi==2018.4.16
cycler==0.10.0
kiwisolver==1.0.1
matplotlib==2.2.2
mne==0.16.1
numpy==1.14.3
pyparsing==2.2.0
python-dateutil==2.7.3
pytz==2018.4
scikit-learn==0.19.1
scipy==1.1.0
six==1.11.0
tornado==5.0.2

**Comment by jasmainak** [comment]
hmm ...

when you do:

```py
>>> import autoreject
>>> autoreject.__version__
```

what do you get?

**Comment by so-phi** [comment]
AttributeError: module 'autoreject' has no attribute '__version__'

**Comment by jasmainak** [comment]
That's weird ...

what about:

```py
>>> autoreject.__path__
```

and what do you get when you do:

```sh
$ pip list | grep autoreject
```

**Comment by so-phi** [comment]
1)
/opt/anaconda3/lib/python3.6/site-packages/autoreject

2)
autoreject      0.1

**Comment by jasmainak** [comment]
I am lost ... it's working for me fine

@agramfort @dengemann any suggestions?

**Comment by so-phi** [comment]
Ah I found the problem. Both my IDEs were using the old autoreject from the general site-packages. Yet pip showed the information for the updated package within the environment. 
Thanks you for the fast replies!

**Comment by jasmainak** [comment]
Glad it worked !
