### ISSUE TITLE
MISC/API/STY

### ISSUE THREAD

**Issue by dengemann** [autoreject/autoreject#11]
Starting to collect a few observations and potential issues here.
1. if following sklearn conventions is a goal it should be `.fix_log_` not `.fix_log`
2. ~~I am wondering if dependencies should be managed more parsimoniously, e.g., refrain from using pandas, the fix log could be dumb matrix.~~
3. ~~dependencies should be caught at construction time, skopt import errors are yelling it me when I'm in the middle of things.~~
4. API: LocalAutoReject / AutoRejectLocal / AutoReject(scope='local')
5. ~~any parallelisation possible? Some bottleneck analyses may help.~~

That's it for now. Adding more things as we proceed. All up for discussion.

**Comment by jasmainak** [comment]
Thanks for the suggestions @dengemann ! I agree that we should remove the pandas dependency. It's easy enough but I was afraid to change things too drastically before we had tests. I think once we have good test coverage, that's definitely one of the things to do. I agree with 1. and 3. as well. Why not 4. too but probably a bit later? I like AutoRejectLocal and AutoRejectGlobal -- makes it more discoverable. But AutoReject(scope='local') may be a drastic change ... Yes it's possible to parallelize the threshold computation!

**Comment by dengemann** [comment]
Ok cool I assume PRs are welcome? Maybe it gives you some time to have fun with PRs on MNE-HCP :)

**Comment by jasmainak** [comment]
yep, PRs are welcome :)

**Comment by dengemann** [comment]
And yes, let's focus on tests first, then urgent low level API and then later public API.

**Comment by jasmainak** [comment]
I think all the issues here have been taken care of
