### ISSUE TITLE
Usage question: Autoreject  + ICA: better on continuous or Epochs?

### ISSUE THREAD

**Issue by DFPV** [autoreject/autoreject#111]
Dear all, 

I would like to use autoreject in my EEG analysis pipeline, but I am having some doubts about when exactly to implement it (in terms of order, before or after ICA?) and on which data (Epoched or continuous?). (I might just be splitting hairs here, but I just want to be sure). Here my concern:

On the autoreject documentation, it is recommended to "first using autoreject to detect the bad segments, then applying ICA, and finally interpolating the bad data.". This apparently assumes that all 3 operations are done on epochs, but I am not sure that is a good idea for my data. For my analysis, I focus on a time window that is narrower than the trial itself, so when I epoch, I effectively drop data (there are different events on each trial, and for now I am only interested in one of them). This makes me believe that, in my case, both ICA and autoreject should work better on the continuous data. 

But then, this might mean that I'd have some duplicated operations (autoreject at least would need to be ran twice, once on continuous data to interpolate/reject overall bad channels, and then on the epochs), and I am not sure how this interacts with ICA. My plan is to extract the components from the continuous data, and then apply the ICA transform on the epochs. However, due to the 2 auto-reject steps, I wonder if this would affect the ICA fitting, since a few extra channels / epochs might be dropped or interpolated after the ICA extraction, but before it applying the ICA correction to the data, and it is generally recommended to re-run the ICA if channels have been interpolated or dropped.

So, I feel I am running in circles, but mostly because I suspect that for my particular case it is better to apply autoreject and ICA on the continuous data, rather than the epochs. 

I suppose my question is, does this concern make any sense? Or would you recommend I simply work with the epoched data and apply all operations on it? (This seems the easiest way to go)

Thanks in advance for any feedback!

**Comment by jasmainak** [comment]
@DFPV autoreject is indeed meant for epoched data but you can use ICA on either raw or epoched data.

One thing that you can do is to use the [make_fixed_length_events](https://www.martinos.org/mne/stable/generated/mne.make_fixed_length_events.html) function in MNE to learn global rejection thresholds, then pass them to ICA. I believe for ICA, you simply need to remove data segments that are really high amplitude. In that sense, you could even get away with setting a conservative threshold and later apply autoreject once you get to the epochs stage. Does that make sense?

**Comment by DFPV** [comment]
Thanks for the suggestion @jasmainak!. But I am not sure I quite get it (I'm still kind of new to EEG in general and very new to MNE-python in particular, so plenty of details still elude me). 

If I understand correctly, the 'make_fixed_length_events' will create epochs that won't discard any data, and I can use that object with the 'get_rejection_thresholds' command (which takes an epoched object as argument), and take those global thresholds as the 'reject' argument in the call to extract the ICA. Then I would go ahead and create the actual epochs object, apply the local autoreject approach to them (to discard / correct bad ones) and finally fit the ICA to those. Is that the idea? If I am understanding correctly, that does seem to take care of my concerns.

Just a follow up question: Would you recommend manually tagging and interpolating bad channels based on the global thresholds from autoreject, before extracting the ICA? 
Thanks again for your very fast feedback!

**Comment by jasmainak** [comment]
> If I understand correctly, the 'make_fixed_length_events' will create epochs that won't discard any data, and I can use that object with the 'get_rejection_thresholds' command (which takes an epoched object as argument),

so far good

> and take those global thresholds as the 'reject' argument in the call to extract the ICA. Then I would go ahead and create the actual epochs object, apply the local autoreject approach to them (to discard / correct bad ones) and finally fit the ICA to those. Is that the idea?

umm ... I am not sure what you mean by "extracting" the ICA. What I was suggesting is to do:

```py
ica.fit(raw, reject=reject)
```
so you can fit the ICA on the epochs object. I would suggest ICA _before_ autoreject if you don't want to end up removing all the trials due to eyeblinks ...

> Just a follow up question: Would you recommend manually tagging and interpolating bad channels based on the global thresholds from autoreject, before extracting the ICA?

I would recommend interpolating only once. So, if you are applying autoreject after ICA, it will do the job for you. It is okay if ICA does not have perfect data. It only needs to be clean enough for the algorithm to extract the ocular and cardiac patterns.

Does that answer your queries?

**Comment by DFPV** [comment]
Great, thanks a lot! That does answer clarify my doubts.

**Comment by sappelhoff** [comment]
@jasmainak I think your suggestion from https://github.com/autoreject/autoreject/issues/111#issuecomment-399439073 regarding fixed length epochs should go to the docs, --> it's not there yet: http://autoreject.github.io/faq.html

**Comment by jasmainak** [comment]
Indeed, do you want to make a PR? :)
