### ISSUE TITLE
Epochs event_id field misaligned after autoreject

### ISSUE THREAD

**Issue by alexrockhill** [autoreject/autoreject#112]
After running ar.fit_transform(epochs), I get an error when the returned epochs are averaged to make and evoked object when autoreject rejects one of more epochs. This is avoided when I delete the event_id entries that corresponded to the dropped epochs. Is this a feature that allows event_id entries to be recovered if the epochs should actually not be dropped or a bug?

**Comment by jasmainak** [comment]
This should not happen. Can you provide a script (using the MNE sample data) to reproduce the error you are getting?

**Comment by agramfort** [comment]
maybe you dropped all epochs from one type of event?

**Comment by jasmainak** [comment]
okay, so issue is solved?

**Comment by alexrockhill** [comment]
Yes, thanks.

Alex

**Comment by jasmainak** [comment]
Great !
