### ISSUE TITLE
ENH/DOC: explain in clear terms why autoreject + interpolation poses no harm to source analysis

### ISSUE THREAD

**Issue by dengemann** [autoreject/autoreject#118]
This is a recurrent question and I heard it 5 times in the last 24 hours. cc @jasmainak @agramfort

**Comment by jasmainak** [comment]
We could add it a note in the [FAQ](http://autoreject.github.io/faq.html). Let me add a few thoughts. We can sharpen this:

- removing artifacts is better than not removing them. It might seem obvious to state it, but probably worth mentioning.
- the rank of the covariance matrix is [estimated automatically in MNE](https://github.com/mne-tools/mne-python/blob/17e1c2906c64e13e1f60213b5422ef7c103eae7c/mne/utils.py#L529) using SVD. There are many methods which reduce the rank of the data and that includes Maxfilter, SSP etc. -- so this is not a new problem and already handled inside MNE.
- if you're really worried, do source estimation per trial and average the result.

**Comment by agramfort** [comment]
I also suggested to Denis to do random interpolation from clean data to
demonstrate
that it does not afffect significantly the source loc eg with a dipole fit
using a phantom.
