### ISSUE TITLE
Save & Load methods

### ISSUE THREAD

**Issue by TomDonoghue** [autoreject/autoreject#119]
It would be nice to have methods available to save and load AutoReject objects. 

Currently I'm just pickling them - but I was also looking into how similar objects are dealt with this, like ICA objects in MNE, which save out to FIFF - but not sure that is needed here. 

Would there be any reason to save and load them with anything other than pickle? 

If pickle makes sense, and it's just a case of adding a quick method to save out to pickle, and a function to load back in - I can probably PR that.

**Comment by jasmainak** [comment]
It seems this is a frequently requested feature, so I'm +1 on a convenience method.

@dengemann I can take a stab at it if you're not opposed to the idea.

**Comment by dengemann** [comment]
Please do! I’ll review.
