### ISSUE TITLE
mne-python externals do not have six any more (pull #5726)

### ISSUE THREAD

**Issue by cmmoenne** [autoreject/autoreject#121]
As I use mne-dev, now I have an `ImportError: cannot import name 'six'` when using autoreject.

**Comment by agramfort** [comment]
fixed by https://github.com/autoreject/autoreject/commit/482d692492c3a86f0656d90a5dff829324ab039c

in master

thx for the bug report

**Comment by jasmainak** [comment]
Thanks @agramfort

**Comment by dasdiptyajit** [comment]
@jasmainak I am having the same issue (ie., can't import 'six'). I am using mne & autoreject -dev version.
