### ISSUE TITLE
autoreject to detect bad channels before MaxFilter

### ISSUE THREAD

**Issue by kalenkovich** [autoreject/autoreject#123]
In [A Reproducible MEG/EEG Group Study](https://www.frontiersin.org/articles/10.3389/fnins.2018.00530/full) you wrote 

> Before running SSS, it is crucial that bad channels are marked, as otherwise SSS may spread the artifacts from the bad channels to all other MEG channels in the data. This step is preferably done manually with visual inspection.

Could you share a few thoughts on why it is better to detect bad channels manually prior to applying MaxFilter? Could `autoreject` be used to detect (but not repair) bad channels at this stage as well?

**Comment by dengemann** [comment]
Yep that could work. You may only end up with cases where autoreject only labels a given bad channel as bad in 99% of the time, which may necessitate using thresholds. But once you fit autoreject you can just use the reject log for deciding about bad channels. Another constraint is that autoreject does not detect flat channels. So checking for a few constantly bad channels prior to maxfilter is not too difficult and conservative. You could also use maxfilters own autobad function but we believe that it is not reliable enough. This is why the mne maxwellfilter code does not offer you autobad. Hope that helps!

**Comment by kalenkovich** [comment]
Thank you for the reply, @dengemann. It sure helps. I am just not sure I understand this point:

> You may only end up with cases where autoreject only labels a given bad channel as bad in 99% of the time, which may necessitate using thresholds.

Do you mean that `autoreject` is overly conservative or the opposite? :-)

Otherwise, do you think the following approach makes sense?

1. Identify flat channels.
2. Use `fit` and then `get_reject_log` on non-flat channels to get candidates for rejection.
3. Select from the candidate pool manually.
4. Run `maxwell_filter` specifying bad channels from 1. and 3.

**Comment by jasmainak** [comment]
>  I am just not sure I understand this point

@kalenkovich let me try to help. The way autoreject works, it tells you bad channels _per epoch_. But it cannot decide for you what channels are globally bad. Thus you would have to make the judgement yourself -- what constitutes as a globally bad channel? Is it when the channel is bad for 99% of the trials or is it when even 80% of the trials are bad? Personally I think it should not matter that much as long as you set something reasonable.

The approach you suggest sounds reasonable to me. Let us know how it goes.

Cheers and merry Xmas!

**Comment by kalenkovich** [comment]
Thank you, @jasmainak and @dengemann !

**Comment by jasmainak** [comment]
Closing the issue as OP was satisfied with the answers.
