### ISSUE TITLE
verbose=False argument gets typecast in save/load, leading to error. 

### ISSUE THREAD

**Issue by TomDonoghue** [autoreject/autoreject#126]
If AutoReject.verbose is set to `False`, then through the save & load procedure, the loaded AutoReject object ends up with the attribute set as 0, which then leads to an error if you try to use that reloaded object to do anything. 

This is only the case for verbose='False' (other verbose settings are fine). 

This example recreates the issue:
```
ar = AutoReject(verbose=False)
ar.save('test_ar.hdf5')
nar = read_auto_reject('test_ar.hdf5')
nar.fit(epochs)
```

The actual error that arises at that point comes from the `_pbar` function, in utilities:
`UnboundLocalError: local variable 'pbar' referenced before assignment`

In '_pbar`, since verbose ends up as 0, nothing triggers, pbar becomes undefined, and it crashes out. 

Fixes:
- I haven't dug into to exactly where/how, but it seems that the save and/or load procedure needs something updating to preserve the `False` as `False` rather than typecasting to 0. 
- Or, if it seems fine to consider 'verbose=0' as valid, then in the `_pbar` function it could check for `if verbose == False`, as opposed to the current `if verbose is False`. 

Related: since verbose can take a set of strings (or False), and these need to match what's defined in `_pbar` for things to work, maybe it would be useful to add a quick check that the verbose argument is valid?
This typo, for example, will give the same 'pbar undefined' error, which isn't super obvious about what's going on / how to debug:
```
ar = AutoReject(verbose='progres')
ar.fit(epochs)
```

If there is an idea for what to do here, I'm happy to make a quick PR.

**Comment by jasmainak** [comment]
So for your first error, it seems the `read_hdf5` and `write_hdf5` functions that I was using from MNE does not like boolean variables. I think it would be better to add a condition during the save and load to check if it's boolean and then if so, convert it to and int with value 0.

> This typo, for example, will give the same 'pbar undefined' error, which isn't super obvious about what's going on / how to debug

Good point! I think we should raise an explicit error inside the [_pbar function](https://github.com/autoreject/autoreject/blob/master/autoreject/utils.py#L162) in autoreject.

PR would be very welcome !
