### ISSUE TITLE
Bridged/shorted channels

### ISSUE THREAD

**Issue by AmirDJV** [autoreject/autoreject#128]
Hi, 

This is less than an issue and more of a question. 

Does autoreject deal/detect bridged/shorted channels? if yes, how? 

Thank you for your all hard and amazing work!

**Comment by jasmainak** [comment]
Hi @AmirDJV no autoreject is only meant for high amplitude artifacts at the moment. It's crucial to remove these for algorithms downstream in the pipeline. However, there are indeed other kinds of artifacts that it does not deal with and bridged channels is one of them.

**Comment by AmirDJV** [comment]
Thank you for your prompt respond :)
