### ISSUE TITLE
Convention for saving autoreject objects to later process in MNE

### ISSUE THREAD

**Issue by AmirDJV** [autoreject/autoreject#132]
Hi, 

Thank you very much for the amazing module and support! 

I'm trying to stick to your (and MNE's) coding conventions and style guides.

After running my epochs through autoreject, I'm ending up with 3 object: 
1. Original epochs. 
2. Autoreject epochs. 
3. Reject log. 

As for now I'm mainly pickling them, I was wondering if there is a convention (or appropriate way) on how I should save them for later use in MNE?.

**Comment by agramfort** [comment]
epochs and autoreject objects have a .save method
for reject log I would use a .mat although agree it's not ideal to separate
the infos

**Comment by AmirDJV** [comment]
For now I'm saving my the original epochs and autoreject epochs using varName.save(varName_epo.fif). 

Would you include a .save method for the reject log in the future?

**Comment by agramfort** [comment]
yes we should add a save to RejectLog

>

**Comment by AmirDJV** [comment]
Great and looking forward for future updates :)

**Comment by jasmainak** [comment]
can I ask why `AutoReject().save()` does not do the job for you? You can simply reapply the transform method on the saved autoreject object to get back the reject log

**Comment by AmirDJV** [comment]
Later on in my work flow I match participants reject logs, so having them already calculated (I think) will make my life easier.  
However, I can see how the use of `AutoReject().save()` could be more elegant code wise.

**Comment by dengemann** [comment]
The reject log can be easily written into a hdf5 file as a dictionary. I think adding a convenience method / function pair would not hurt.
