### ISSUE TITLE
RANSAC - Error in bad_log array when n_jobs > 1

### ISSUE THREAD

**Issue by LegrandNico** [autoreject/autoreject#136]
Using n_jobs > 1 with Ransac lead to a corrupted bad_log array, showing the repetition of the same pattern n times. This can be reproduced directly from the example: https://autoreject.github.io/auto_examples/plot_ransac.html 

**n_jobs=1**

![njob_1](https://user-images.githubusercontent.com/27711796/56533285-ae291980-6557-11e9-94de-bc390e4e6fd1.png)

**n_jobs=10**
![njob_10](https://user-images.githubusercontent.com/27711796/56533325-bc773580-6557-11e9-9bb6-c5cd6f328567.png)

**Comment by agramfort** [comment]
this needs a fix here:

https://github.com/autoreject/autoreject/blob/master/autoreject/ransac.py#L200

pb is the following. When you spawn a new process you inherit the
random_state so each process starts to use the same random state.

Solution : pass a seed to child process or precompute the random stuff
before the parallel call. Can you give it a try?

>

**Comment by LegrandNico** [comment]
Hello Alex, thanks for the reply, I am currently travelling so I will try to work on it next week if the issue is still open.

Just to be sure: do you think this bug only concerns the bad_log array or is the clean_epochs also impacted?

**Comment by agramfort** [comment]
I don't know.

**Comment by jasmainak** [comment]
let's assume both unless otherwise found. A fix is welcome!

**Comment by jasmainak** [comment]
closed by #138
