### ISSUE TITLE
erorr with joblib parallel

### ISSUE THREAD

**Issue by yvonnio** [autoreject/autoreject#137]
Hi guys,
I'm having issues running ransac after updating autoreject to the latest dev version.  I updated to fix another issue (#121) since I'm using mne-dev.  My new error seems to stem from sklearn parallel backends.

```
ransac = Ransac(verbose='progressbar', n_jobs=1)
epochs_clean = ransac.fit_transform(epochs)
```

> Traceback (most recent call last):
> 
>   File "<ipython-input-121-e6c95c6e4a2b>", line 2, in <module>
>     epochs_clean = ransac.fit_transform(epochs)
> 
>   File "/dagher/dagher6/yyau/toolbox/anaconda3/envs/mne/lib/python3.6/site-packages/autoreject/ransac.py", line 229, in fit_transform
>     return self.fit(epochs).transform(epochs)
> 
>   File "/dagher/dagher6/yyau/toolbox/anaconda3/envs/mne/lib/python3.6/site-packages/autoreject/ransac.py", line 202, in fit
>     n_jobs))
> 
>   File "/dagher/dagher6/yyau/toolbox/anaconda3/envs/mne/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 874, in __call__
>     n_jobs = self._initialize_backend()
> 
>   File "/dagher/dagher6/yyau/toolbox/anaconda3/envs/mne/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 673, in _initialize_backend
>     **self._backend_args)
> 
>   File "/dagher/dagher6/yyau/toolbox/anaconda3/envs/mne/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 471, in configure
>     SequentialBackend(nesting_level=self.nesting_level))
> 
> FallbackToBackend: <sklearn.externals.joblib._parallel_backends.SequentialBackend object at 0x7f98c2a15128>

This is my setup from `mne.sys_info()`:

> Platform:      Linux-4.9.137-i686-64-smp-x86_64-with-debian-jessie-sid
> Python:        3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)  [GCC 7.3.0]
> Executable:    /dagher/dagher6/yyau/toolbox/anaconda3/envs/mne/bin/python
> CPU:           x86_64: 16 cores
> Memory:        31.3 GB
> 
> mne:           0.18.dev0
> numpy:         1.16.2 {blas=mkl_rt, lapack=mkl_rt}
> scipy:         1.2.0
> matplotlib:    3.0.2 {backend=Qt5Agg}
> 
> sklearn:       0.20.3
> nibabel:       2.3.3
> mayavi:        4.7.0.dev0 {qt_api=pyqt5, PyQt5=5.9.2}
> cupy:          Not found
> pandas:        0.24.1
> dipy:          0.15.0

Any ideas?

**Comment by jasmainak** [comment]
Not sure, try using joblibs directly and if it fixes it. PR to fix it would be welcome

**Comment by yvonnio** [comment]
My temporary solution thus far has been to uninstall autoreject, pip install autoreject again (version 0.1) and then manually change the autoreject/utils.py as in the commit for this issue #121 .  This works fine and I have no problem running ransac or autoreject with n_jobs=6.

I'm not sure how to run it with joblibs directly.

**Comment by jasmainak** [comment]
Oh I see your issue. You should not manually edit your install. Instead, install the development version ...

**Comment by yvonnio** [comment]
Maybe I should clarify, I did install the development version using `pip install https://api.github.com/repos/autoreject/autoreject/zipball/master` which gave me my original issue with joblibs.  I can overcome this issue by doing my "manual editing" method which is clearly far from ideal.

**Comment by jasmainak** [comment]
hmm ... in that case, it might be worth going back on the commits and seeing which commit breaks things. You could use "git bisect" for this purpose. It will help someone else not relearn the same lessons and have a clean solution in the master

**Comment by jasmainak** [comment]
closing this issue as it has been fixed in master. We need to make a release for a more permanent fix.
