### ISSUE TITLE
ECG missing in get_rejection_threshold results

### ISSUE THREAD

**Issue by kalenkovich** [autoreject/autoreject#139]
The docstring for `autoreject.get_rejection_threshold` states that 'ecg' should be in the returned `reject` dictionary:

    Returns
    -------
    reject : dict
        The rejection dictionary with keys 'mag', 'grad', 'eeg', 'eog'
        and 'ecg'.

But then the iteration over channel types skips ECG:

    for ch_type in ['mag', 'grad', 'eeg', 'eog']:

Is this done on purpose? Should a different method be used to estimate the ECG rejection threshold?

**Comment by dengemann** [comment]
Thanks for reporting. This is a bug. The 'ecg' should not appear in the documentation.
