### ISSUE TITLE
Bad channels not detected

### ISSUE THREAD

**Issue by jgeller112** [autoreject/autoreject#142]
Hello, 

I am working with data where some of the Ss have cochlear implants--this creates some pretty noisy data. For reference, I am applying autoreject after ICA to EEG data.

```
def apply_ica(subject, ica_apply_path, ica_path, epo_path, overwrite):
    
    ica_epochs_name = subject + 'clean1' + '-ica-epo.fif'        
    ica_epochs_path = ica_apply_path + ica_epochs_name
        
    if overwrite or not isfile(ica_epochs_path):

        epochs = mne.read_epochs(epo_path+subject+ '-epo.fif')
        ica = read_ica(ica_path + subject + '-ica.fif')
        ica_channels = ica_channels_dict[subject]# in
        ica_epochs = ica.apply(epochs, exclude=ica_channels)
        
        ica_epochs.save(ica_epochs_path)
       
``` 
Even after applying ICA, I get something like this:
![image](https://user-images.githubusercontent.com/18429968/58059383-389e7200-7b32-11e9-8fcb-fab35604b8dc.png)

```
def autoreject_epochs(subject,ica_apply_path, clean_path, overwrite):
    ar = AutoReject()
    ica_epochs = mne.read_epochs(clean_path+subject+'-ica-epo.fif')
    epochs_clean = ar.fit_transform(ica_epochs)
    clean_epochs_name= subject + 'ar' + '-epo.fif'      
    ica_epochs_path = clean_path + clean_epochs_name
    epochs_clean.save(ica_epochs_path)
```
I figured autoreject might clean this up, but it does not: 

![image](https://user-images.githubusercontent.com/18429968/58059187-823a8d00-7b31-11e9-8cb9-887416ea0acd.png)

I am wondering if the electrical output from the implant is just too much to overcome? Any suggestions?

**Comment by jasmainak** [comment]
hi @jgeller112 it looks to me that you need to highpass filter your data first. There are dc offsets and autoreject is not meant for this.

**Comment by jgeller112** [comment]
I did high-pass filter at  1hz. Would you recommend a different high-pass filter?

**Comment by jasmainak** [comment]
Then I don't understand why there are these offsets even after highpass filtering. You need to look closer into your data.

**Comment by jgeller112** [comment]
It looks like a 2Hz filter gets rid of those offsets. Thanks for your help! I appreciate it.

**Comment by jasmainak** [comment]
okay good to know! :) Closing issue
