### ISSUE TITLE
DOC: Provide "intuition" on what autoreject does

### ISSUE THREAD

**Issue by sappelhoff** [autoreject/autoreject#144]
The paper on autoreject explains most of the details to understand the code. However, it's not a very easy read and I think that the docs would benefit from a small section providing an "intuition" on how autoreject works.

A possible place could be in the [FAQ](http://autoreject.github.io/faq.html).

Below I paste a first draft of what I envision such a "intuition" to be like for autoreject global.

Feel free to add comments on that text in this [Gdoc](https://docs.google.com/document/d/1jU6NleGgNvW2qcCh41Qt0WTBnaDntqDjY_5w6WEikm8/edit?usp=sharing)

---

autoreject global
=================
- Given some data with multiple trials (epochs) that contain sensor X timepoints data
- We want to find a threshold T in microvolts that will reject noisy epochs and retain clean epochs
- Do the following for a set of possible candidate thresholds Ts
- For each T:
    - Split your data into K folds (=k equal parts) along the trial dimension
        - Each of the k parts will be a "test" set once, while the others will be combined to be a "train" set
    - Then for each fold k (consisting of train and test trials) do:
        - apply threshold T to reject trials in the train set
        - calculate the mean of the signal (for each sensor and timepoint) over the GOOD trials in the train set
        - calculate the *median* of the signal (for each sensor and timepoint) over ALL trials in the test set
        - compare both of these signals and calculate the error (frobenius norm of their difference)
        - save the error
    - Now we have k errors
    - Form the mean error (over all k errors) associated with our current threshold T in microvolts
    - Save the mapping of current T to its error

- ... now we have a set of Ts all mapped to their specific error 
- the T with the lowest error is the best rejection threshold for a global rejection

**Comment by jasmainak** [comment]
Do you think this example could be molded into a tutorial: http://autoreject.github.io/auto_examples/plot_global_reject.html#sphx-glr-auto-examples-plot-global-reject-py with the points above that you mention?

Something that I've done in the past is to show the evoked for different rejection thresholds. For example [here](https://jasmainak.github.io/mne-workshop-brown/preprocessing/autoreject.html#tuning-rejection-thresholds) I made an interactive widget to show this but one could very well just plot the evoked for different set of thresholds.

**Comment by sappelhoff** [comment]
> Do you think this example could be molded into a tutorial

yes, that's an option ... however I think that providing it in the FAQ would give it more visibility ... so users don't "discover it by accident" when going through the examples, but rather: they have a question, they go to FAQ, they find a table of questions (not yet there, but we should add it as FAW grows), and they go to what they are interested in.

the widget does not really work - there are no buttons or "knobs" to turn for any of the plots :thinking:

**Comment by jasmainak** [comment]
hmm ... the FAQ is more a place for things that are like "discussion" -- should I do X or should I do Y? I don't want to mix it with things that describe the model. 

Perhaps we could add another section called "model" or "algorithm" or "tutorial" to the navbar so it's easy to discover? In sphinx gallery you can have different directories for different kinds of examples so this example can be moved to that and it won't be "discover by accident".

> the widget does not really work - there are no buttons or "knobs" to turn for any of the plots

yes that's true but it would work if you downloaded the notebook and ran it :) Unfortunately the jupyter-book integration for widgets was late and I didn't want to mess with my current setup so I didn't update it.
