### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by jgeller112** [autoreject/autoreject#150]
Hello, 

I updated to the new version of AR and encountered an issue that I did not have before: 
```
 ica_epochs = mne.read_epochs(reref_path +subject+ 'rerefaica'+'-epo.fif')
 ar = AutoReject(ica_epochs.info)
 epochs_clean = ar.fit_transform(ica_epochs)
```
Error: 
clean_by_interp() got an unexpected keyword argument 'dots'

**Comment by jasmainak** [comment]
Can you post why you closed this? I suppose you didn't have the right version?

**Comment by jgeller112** [comment]
I updated some of the dependancies and it seemed to solve the problem.
