### ISSUE TITLE
Making reject_log.plot() more flexible

### ISSUE THREAD

**Issue by mkoculak** [autoreject/autoreject#151]
Hi,
first of all, many thanks for this awesome library.

I am doing a lot of fairly automatic preprocessing on EEG data and would like to generate plots for each autoreject cleaning that I can inspect later for a sanity check.

The existing plot function does not enable to capture the figure and modify it or save.
Also my data contains ~2000 epochs and 64 channels, which makes the plot really difficult to look at (really tall and slim).

I have made a simple hack, that does the trick for me. Do you think it is worthwhile to make a pull request? Or maybe you have a better solution?

```python
def plot(self, show=True):
    """Plot. Returns a figure."""
    import matplotlib.pyplot as plt

    figure = plt.figure(figsize=(12, 6))
    ax = plt.gca()
    ax.grid(False)
    ch_names_ = self.ch_names[7::10]
    
    if self.labels.shape[0] > self.labels.shape[1]:
        plt.imshow(self.labels.T, cmap='Reds',
                   interpolation='nearest')
        ax.set_xlabel('Epochs')
        ax.set_ylabel('Channels')
        plt.setp(ax, yticks=range(7, self.labels.shape[1], 10),
                 yticklabels=ch_names_)
    else:
        plt.imshow(self.labels, cmap='Reds',
                   interpolation='nearest')
        ax.set_xlabel('Channels')
        ax.set_ylabel('Epochs')
        plt.setp(ax, xticks=range(7, self.labels.shape[1], 10),
                 xticklabels=ch_names_)
        
    # XXX to be fixed
    plt.setp(ax.get_yticklabels(), rotation=0)
    plt.setp(ax.get_xticklabels(), rotation=90)
    ax.tick_params(axis=u'both', which=u'both', length=0)
    plt.tight_layout(rect=[None, None, None, 1.1])
    if show:
        plt.show()
    return figure
```

**Comment by jasmainak** [comment]
Pull requests are absolutely welcome! In fact, it's probably preferred over this since here I can't see what you changed. Thanks a lot.

**Comment by mkoculak** [comment]
Right!
Made a pull request here: https://github.com/autoreject/autoreject/pull/152
