### ISSUE TITLE
autoreject import failing with mne python master

### ISSUE THREAD

**Issue by sappelhoff** [autoreject/autoreject#153]
with mne-python dev installation and autoreject pip (latest pypi) installation, `import autoreject` yields the following:

(error not present when using mne-python 0.18.2)

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-dcfa2da527e7> in <module>
----> 1 import autoreject

~/miniconda3/envs/mne/lib/python3.6/site-packages/autoreject/__init__.py in <module>
      1 __version__ = '0.2'
      2 
----> 3 from .autoreject import _GlobalAutoReject, _AutoReject, AutoReject
      4 from .autoreject import RejectLog, read_auto_reject
      5 from .autoreject import compute_thresholds, validation_curve, get_rejection_threshold

~/miniconda3/envs/mne/lib/python3.6/site-packages/autoreject/autoreject.py in <module>
     25                     _get_picks_by_type, _pprint)
     26 from .bayesopt import expected_improvement, bayes_opt
---> 27 from .viz import plot_epochs
     28 
     29 _INIT_PARAMS = ('consensus', 'n_interpolate', 'picks',

~/miniconda3/envs/mne/lib/python3.6/site-packages/autoreject/viz.py in <module>
     18 from mne.io.pick import pick_types, channel_type
     19 from mne.io.proj import setup_proj
---> 20 from mne.viz.utils import (figure_nobar, _toggle_proj, _toggle_options,
     21                            _layout_figure, _channels_changed,
     22                            _plot_raw_onscroll, _onclick_help, plt_show,

ImportError: cannot import name '_layout_figure'



```

**Comment by jasmainak** [comment]
arggh ... this was bound to happen. @agramfort are you open to adding an argument to the epochs plotting code in MNE so that we avoid duplicating and breaking autoreject with every release of MNE?

**Comment by agramfort** [comment]
you want to pass the autoreject labels? yes it seems reasonable to me.

>

**Comment by jasmainak** [comment]
yep exactly

**Comment by sappelhoff** [comment]
with the MNE python 0.19 release out there now, this problem is now present in a standard installation :-)

Is there a workaround for now?

**Comment by jasmainak** [comment]
I will take care of this first thing in the sprint next week. Sorry for the trouble.

**Comment by jgeller112** [comment]
Any update on when this will be fixed?

**Comment by davestanley** [comment]
Got the same issue. I was able to fix it by commenting out all the `_layout_figure(params)` lines and removing the import. (At least, this did not break the plot_auto_repair.py demo)

**Comment by jgeller112** [comment]
@davestanley, Do you mind sharing your script? I cant get mine to work on my data.

**Comment by davestanley** [comment]
@jgeller112 I have an updated version with the lines commented out in my fork here: https://github.com/davestanley/autoreject

The script I was using to test it is available here: https://autoreject.github.io/auto_examples/plot_auto_repair.html#sphx-glr-auto-examples-plot-auto-repair-py

**Comment by jasmainak** [comment]
Please update to the development version of `autoreject`, it should be fixed now
