### ISSUE TITLE
RejectLog.labels has dimensions different from how described in the docs

### ISSUE THREAD

**Issue by sappelhoff** [autoreject/autoreject#162]
The [docs](https://autoreject.github.io/generated/autoreject.RejectLog.html#autoreject.RejectLog) on RejectLog.labels say that:

> labels: array, shape (n_channels, n_epochs)

However, running my own code and the examples I find that the shape is actually `n_epochs, n_channels`

You can replicate this by running the [auto repair example](https://autoreject.github.io/auto_examples/plot_auto_repair.html#sphx-glr-auto-examples-plot-auto-repair-py) and at the line

```
epochs_clean = ar.transform(epochs['Auditory/Left'])
```

you add the `return_log=True` parameter and direct the input to `epochs_clean, report`

then you can prove my point that `n_channels` is in the 2nd dimension instead of the 1st, as advertised by the docs:

```
In [14]: report.labels.shape                                                        
Out[14]: (145, 376)

In [15]: len(report.ch_names)                                                       
Out[15]: 376



```

**Comment by jasmainak** [comment]
indeed you are right, do you want to make a PR to fix it?
