### ISSUE TITLE
autoreject() usage and channel information

### ISSUE THREAD

**Issue by neerajww** [autoreject/autoreject#164]
autoreject() usage and channel information
The ar.fir_transform() gets hanged if the channel location has 'nans'. Example:
ar = AutoReject()
epochs_clean = ar.fit_transform(epochs)
Running autoreject on ch_type=eeg
0.00% Creating augmented epochs (struck here)

Expected results
Throwing an error and the reason will be better.

**Comment by jasmainak** [comment]
Can you provide a reproducible script? This issue seems very similar to this one: https://github.com/autoreject/autoreject/issues/124#issue-401554096. Perhaps you can base it off that one?

Also -- can you confirm that you use the latest version of autoreject?

**Comment by neerajww** [comment]
Here is the script to replicate the error. The Version is 0.3.dev0. The bug is SIMILAR but not SAME to the thread you have linked to.
`"""
A test script to test the channel location usage in autoreject 
Version: 0.3.dev0
"""

import mne
import numpy as np
import autoreject
from functools import partial
from autoreject import AutoReject
import matplotlib.pyplot as plt


###############################################################################
# Some metadata
# Read a montage to set channels etc
montage = mne.channels.read_montage('biosemi16')
channel_names = montage.ch_names
channel_types = montage.ch_names

# Init somethings about the recording
sfreq = 10
data = np.random.randn(20, 19, sfreq * 2)
info = mne.create_info(
    ch_names=montage.ch_names,
    ch_types=['eeg']*len(montage.ch_names),
    sfreq=sfreq,
)
info['description'] = 'My custom dataset'
###############################################################################
# Event info
events = np.array([
    [0, 20, 1],
    [1, 20, 2],
    [2, 20, 1],
    [3, 20, 2],
    [4, 20, 1],
    [5, 20, 2],
    [6, 20, 1],
    [7, 20, 2],
    [8, 20, 1],
    [9, 20, 2],
    [10, 20, 1],
    [11, 20, 2],
    [12, 20, 1],
    [13, 20, 2],
    [14, 20, 1],
    [15, 20, 2],
    [16, 20, 1],
    [17, 20, 2],
    [18, 20, 1],
    [19, 20, 2],
])
tmin = 0
###############################################################################
# Create Epoch object
epochs  = mne.EpochsArray(data, info, events, tmin)

###############################################################################
# Apply montage
montage = mne.channels.read_montage('biosemi16')
for j in range(len(epochs.ch_names)):
    epochs.ch_names[j] = montage.ch_names[j]
    epochs.info['chs'][j]['ch_name'] = montage.ch_names[j]
epochs.set_montage(montage,set_dig=True)

###############################################################################
# set last channel loc to nans
epochs.info['chs'][-1]['loc'][:] =  np.NaN

###############################################################################
# run autoreject
ar = AutoReject(random_state=42)
epochs_clean = ar.fit_transform(epochs)`

**Comment by jasmainak** [comment]
I can confirm that I can reproduce your problem with MNE v0.18. Thanks a lot for the bug report

**Comment by agramfort** [comment]
do you know what is the fix?

>
