### ISSUE TITLE
Question: Fit or transform autoreject of multiple event ids in one call

### ISSUE THREAD

**Issue by zuxfoucault** [autoreject/autoreject#172]
I have a question regarding the usage, not sure if it is appropriate to post it here?

In this [example](https://699-59485140-gh.circle-artifacts.com/0/html/auto_examples/plot_auto_repair.html#sphx-glr-auto-examples-plot-auto-repair-py), autoreject fit and transform are applied to one event id in each function call. Is it appropriate to fit or transform to multiple event ids in one call. For example,

`ar.fit(epochs)` rather than `ar.fit(epochs['Auditory/Left'])`
`ar.transform(epochs)` rather than `ar.transform(epochs['Auditory/Left'])`

Thanks!

**Comment by jasmainak** [comment]
> I have a question regarding the usage, not sure if it is appropriate to post it here?

It's the right place to ask!

> Is it appropriate to fit or transform to multiple event ids in one call.

I'd say it doesn't matter.

**Comment by zuxfoucault** [comment]
thanks!
