### ISSUE TITLE
bug "Unknown argument(s): {'spinner': True}"

### ISSUE THREAD

**Issue by elvisjade** [autoreject/autoreject#173]
when I try to use autoreject to Automatically repair epochs it will report a bug  "Unknown argument(s): {'spinner': True}" 
my code is 
ar = AutoReject(n_interpolates, consensus_percs, picks=picks,
                thresh_method='random_search', random_state=42)
the bug report is 
Note that fitting and transforming can be done on different compatible
portions of data if needed.
ar.fit(epochs['Auditory/Left'])
epochs_clean = ar.transform(epochs['Auditory/Left'])
evoked_clean = epochs_clean.average()
evoked = epochs['Auditory/Left'].average()

I'm using the same code in 
https://699-59485140-gh.circle-artifacts.com/0/html/auto_examples/plot_auto_repair.html#sphx-glr-auto-examples-plot-auto-repair-py

and when i try to use autoreject to detect bad sensors using RANSAC it will report a same  bug  "Unknown argument(s): {'spinner': True}" 
the code is 
from autoreject import Ransac  # noqa
from autoreject.utils import interpolate_bads  # noqa

ransac = Ransac(verbose='progressbar', picks=picks, n_jobs=1)
epochs_clean = ransac.fit_transform(epochs)

the bug report is 
~/opt/anaconda3/envs/mne3/lib/python3.7/site-packages/mne/externals/tqdm/_tqdm/std.py in __init__(self, iterable, desc, total, leave, file, ncols, mininterval, maxinterval, miniters, ascii, disable, unit, unit_scale, dynamic_ncols, smoothing, bar_format, initial, position, postfix, unit_divisor, write_bytes, lock_args, gui, **kwargs)
    941                     fp_write=getattr(file, 'write', sys.stderr.write))
    942                 if "nested" in kwargs else
--> 943                 TqdmKeyError("Unknown argument(s): " + str(kwargs)))
    944 
    945         # Preprocess the arguments

TqdmKeyError: "Unknown argument(s): {'spinner': True}"

I'm using the same code in 
https://699-59485140-gh.circle-artifacts.com/0/html/auto_examples/plot_ransac.html#sphx-glr-auto-examples-plot-ransac-py

my computer is MacBook 2017(10.14.6 ) and  code environment is 

 packages in environment at /Users/~/opt/anaconda3/mne3:

Name                    Version                   Build  Channel
alabaster                 0.7.12                   py37_0  
appdirs                   1.4.3                    pypi_0    pypi
applaunchservices         0.2.1                      py_0  
appnope                   0.1.0                    py37_0  
apptools                  4.5.0                    pypi_0    pypi
argh                      0.26.2                   py37_0  
asn1crypto                1.3.0                    py37_0  
astroid                   2.3.3                    py37_0  
atomicwrites              1.3.0                    py37_1  
attrs                     19.3.0                     py_0  
autopep8                  1.4.4                      py_0  
autoreject                0.2.1                    pypi_0    pypi
babel                     2.8.0                      py_0  
backcall                  0.1.0                    py37_0  
blas                      1.0                         mkl  
bleach                    3.1.0                    py37_0  
ca-certificates           2020.1.1                      0  
certifi                   2019.11.28               py37_1  
cffi                      1.13.2           py37hb5b8e2f_0  
chardet                   3.0.4                 py37_1003  
cloudpickle               1.2.2                      py_0  
codespell                 1.16.0                   pypi_0    pypi
configobj                 5.0.6                    pypi_0    pypi
coverage                  5.0              py37h1de35cc_0  
cryptography              2.8              py37ha12b0ac_0  
cycler                    0.10.0                   py37_0  
dbus                      1.13.12              h90a0687_0  
decorator                 4.4.1                      py_0  
defusedxml                0.6.0                      py_0  
diff-match-patch          20181111                   py_0  
dipy                      1.1.1                    pypi_0    pypi
docutils                  0.15.2                   py37_0  
entrypoints               0.3                      py37_0  
envisage                  4.9.0                    pypi_0    pypi
et_xmlfile                1.0.1                    py37_0  
expat                     2.2.6                h0a44026_0  
flake8                    3.7.9                    py37_0  
freetype                  2.9.1                hb4e5f40_0  
future                    0.18.2                   py37_0  
gettext                   0.19.8.1             h15daf44_3  
glib                      2.63.1               hd977a24_0  
h5py                      2.9.0            py37h3134771_0  
hdf5                      1.10.4               hfa1e0ec_0  
icu                       58.2                 h4b95b61_1  
idna                      2.8                      py37_0  
imageio                   2.6.1                    pypi_0    pypi
imagesize                 1.2.0                      py_0  
importlib_metadata        1.3.0                    py37_0  
intel-openmp              2019.4                      233  
intervaltree              3.0.2                      py_0  
ipykernel                 5.1.3            py37h39e3cac_1  
ipython                   7.11.1           py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.5.1                      py_0  
isort                     4.3.21                   py37_0  
jdcal                     1.4.1                      py_0  
jedi                      0.14.1                   py37_0  
jinja2                    2.10.3                     py_0  
joblib                    0.14.1                     py_0  
jpeg                      9b                   he5867d9_2  
json5                     0.8.5                      py_0  
jsonschema                3.2.0                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.3.4                    py37_0  
jupyter_console           6.1.0                      py_0  
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1                    py37_0    conda-forge
jupyter_core              4.6.1                    py37_0  
jupyter_highlight_selected_word 0.2.0                 py37_1000    conda-forge
jupyter_latex_envs        1.4.4                 py37_1000    conda-forge
jupyter_nbextensions_configurator 0.4.1                    py37_0    conda-forge
jupyterlab                1.2.5              pyhf63ae98_0  
jupyterlab_server         1.0.6                      py_0  
jupyterthemes             0.20.0                   pypi_0    pypi
keyring                   20.0.0                   py37_0  
kiwisolver                1.1.0            py37h0a44026_0  
lazy-object-proxy         1.4.3            py37h1de35cc_0  
lesscpy                   0.14.0                   pypi_0    pypi
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.37               ha441bb4_0  
libsodium                 1.0.16               h3efe00b_0  
libspatialindex           1.9.3                h0a44026_0  
libtiff                   4.1.0                hcb84e12_0  
libxml2                   2.9.9                hf6e021a_1  
libxslt                   1.1.33               h33a18ac_0  
llvm-openmp               4.0.1                hcfea43d_1  
llvmlite                  0.31.0           py37h1341992_0  
lxml                      4.5.0            py37hef8c89e_0  
markupsafe                1.1.1            py37h1de35cc_0  
matplotlib                3.1.1            py37h54f8f79_0  
mayavi                    4.7.1                    pypi_0    pypi
mccabe                    0.6.1                    py37_1  
meshio                    3.3.1                    pypi_0    pypi
mistune                   0.8.4            py37h1de35cc_0  
mkl                       2019.4                      233  
mkl-service               2.3.0            py37hfbe908c_0  
mkl_fft                   1.0.15           py37h5e564d8_0  
mkl_random                1.1.0            py37ha771720_0  
mne                       0.20.0                   pypi_0    pypi
more-itertools            8.0.2                      py_0  
nbconvert                 5.6.1                    py37_0  
nbformat                  4.4.0                    py37_0  
ncurses                   6.1                  h0a44026_1  
neo                       0.8.0                    pypi_0    pypi
nibabel                   3.0.0                    pypi_0    pypi
nilearn                   0.6.1                    pypi_0    pypi
notebook                  6.0.3                    py37_0  
numba                     0.47.0           py37h6440ff4_0  
numexpr                   2.7.0            py37h7413580_0  
numpy                     1.18.1           py37h7241aed_0  
numpy-base                1.18.1           py37h6575580_1  
numpydoc                  1.0.0.dev0               pypi_0    pypi
olefile                   0.46                     py37_0  
openpyxl                  3.0.3                      py_0  
openssl                   1.1.1e               h1de35cc_0  
packaging                 20.0                       py_0  
pandas                    0.25.3           py37h0a44026_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
parso                     0.5.2                      py_0  
pathtools                 0.1.2                      py_1  
patsy                     0.5.1                    py37_0  
pcre                      8.43                 h0a44026_0  
pexpect                   4.7.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    7.0.0            py37h4655f20_0  
pip                       19.3.1                   py37_0  
pluggy                    0.13.1                   py37_0  
ply                       3.11                     pypi_0    pypi
prometheus_client         0.7.1                      py_0  
prompt_toolkit            3.0.2                      py_0  
psutil                    5.6.7            py37h1de35cc_0  
ptyprocess                0.6.0                    py37_0  
py                        1.8.1                      py_0  
pycodestyle               2.5.0                    py37_0  
pycparser                 2.19                     py37_0  
pydocstyle                5.0.2                    pypi_0    pypi
pyface                    6.1.2                    py37_0  
pyflakes                  2.1.1                    py37_0  
pygments                  2.5.2                      py_0  
pylint                    2.4.4                    py37_0  
pyopenssl                 19.1.0                   py37_0  
pyparsing                 2.4.6                      py_0  
pyqt                      5.9.2            py37h655552a_2  
pyqt5                     5.10                     pypi_0    pypi
pyqt5-sip                 12.7.0                   pypi_0    pypi
pyrsistent                0.15.6           py37h1de35cc_0  
pysocks                   1.7.1                    py37_0  
pysurfer                  0.9.0                    pypi_0    pypi
pytest                    5.3.2                    py37_0  
pytest-cov                2.8.1                      py_0  
pytest-faulthandler       2.0.1                    pypi_0    pypi
pytest-mock               1.13.0                     py_1  
pytest-sugar              0.9.2                    pypi_0    pypi
pytest-timeout            1.3.3                    py37_0  
python                    3.7.6                h359304d_2  
python-dateutil           2.8.1                      py_0  
python-jsonrpc-server     0.3.2                      py_0  
python-language-server    0.31.2                   py37_0  
python-picard             0.4                      pypi_0    pypi
python.app                2                        py37_9  
pytz                      2019.3                     py_0  
pyvista                   0.23.0                   pypi_0    pypi
pyyaml                    5.2              py37h1de35cc_0  
pyzmq                     18.1.0           py37h0a44026_0  
qdarkstyle                2.7                        py_0  
qt                        5.9.7                h468cd18_1  
qtawesome                 0.6.0                      py_0  
qtconsole                 4.6.0                      py_1  
qtpy                      1.9.0                      py_0  
quantities                0.12.4                   pypi_0    pypi
readline                  7.0                  h1de35cc_5  
requests                  2.22.0                   py37_1  
restpython                1.1.2                    pypi_0    pypi
rope                      0.14.0                     py_0  
rtree                     0.8.3                    py37_0  
scikit-learn              0.22.1           py37h27c97d8_0  
scipy                     1.3.1            py37h1410ff5_0  
scooby                    0.5.0                    pypi_0    pypi
send2trash                1.5.0                    py37_0  
setuptools                44.0.0                   py37_0  
sip                       4.19.8                   pypi_0    pypi
six                       1.13.0                   py37_0  
sklearn                   0.0                      pypi_0    pypi
snowballstemmer           2.0.0                      py_0  
sortedcontainers          2.1.0                    py37_0  
sphinx                    2.3.1                      py_0  
sphinxcontrib-applehelp   1.0.1                      py_0  
sphinxcontrib-devhelp     1.0.1                      py_0  
sphinxcontrib-htmlhelp    1.0.2                      py_0  
sphinxcontrib-jsmath      1.0.1                      py_0  
sphinxcontrib-qthelp      1.0.2                      py_0  
sphinxcontrib-serializinghtml 1.1.3                      py_0  
spyder                    4.0.1                    py37_0  
spyder-kernels            1.8.1                    py37_0  
sqlite                    3.30.1               ha441bb4_0  
statsmodels               0.10.1           py37h1d22016_0  
tbb                       2019.8               h04f5b5a_0  
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.3                    py37_0  
testpath                  0.4.4                      py_0  
tk                        8.6.8                ha441bb4_0  
tornado                   6.0.3            py37h1de35cc_0  
traitlets                 4.3.3                    py37_0  
traits                    5.2.0            py37h1de35cc_0  
traitsui                  6.1.3                      py_0  
ujson                     1.35             py37h1de35cc_0  
urllib3                   1.25.7                   py37_0  
vtk                       8.1.2                    pypi_0    pypi
watchdog                  0.9.0                    py37_1  
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
wheel                     0.33.6                   py37_0  
widgetsnbextension        3.5.1                    py37_0  
wrapt                     1.11.2           py37h1de35cc_0  
wurlitzer                 2.0.0                    py37_0  
xlrd                      1.2.0                    py37_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
yapf                      0.28.0                     py_0  
zeromq                    4.3.1                h0a44026_3  
zipp                      0.6.0                      py_0  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.3.7                h5bba6e5_0

**Comment by sustianovich** [comment]
It happens to me the same in the jupyterlab notebook for example with the rest of function as "ar.fit(epochs)".
I think it does it ok in Pycharm.

**Comment by jasmainak** [comment]
I suspect it's related to the new MNE release and [this pull request](https://github.com/mne-tools/mne-python/pull/7155). I'll take a look next next week. Thanks for reporting.

**Comment by elvisjade** [comment]
> I suspect it's related to the new MNE release and [this pull request](https://github.com/mne-tools/mne-python/pull/7155). I'll take a look next next week. Thanks for reporting. In the meanwhile, you can use the older MNE version.

so I need to use pycharm or use the old version mne(like0.19)?

**Comment by elvisjade** [comment]
> I suspect it's related to the new MNE release and [this pull request](https://github.com/mne-tools/mne-python/pull/7155). I'll take a look next week. Thanks for reporting. In the meanwhile, you can use the older MNE version.

I have tried to use pycharm to analyze this data. the function (Find global rejection threshold)is ok, but Automatically repair epochs still don't work.
the bug report is 

Running autoreject on ch_type=grad
Traceback (most recent call last):
  File "/Users/ opt/anaconda3/envs/mne3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-fce261f71b7b>", line 1, in <module>
    runfile('/Volumes/secondlife/download/plot_auto_repair (1).py', wdir='/Volumes/secondlife/download')
  File "/Volumes/secondlife/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Volumes/secondlife/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Volumes/secondlife/download/plot_auto_repair (1).py", line 103, in <module>
    ar.fit(epochs['Auditory/Left'])
  File "/Users/ opt/anaconda3/envs/mne3/lib/python3.7/site-packages/autoreject/autoreject.py", line 1006, in fit
    self.verbose)
  File "/Users/ opt/anaconda3/envs/mne3/lib/python3.7/site-packages/autoreject/autoreject.py", line 763, in _run_local_reject_cv
    local_reject.fit(epochs)
  File "/Users/ opt/anaconda3/envs/mne3/lib/python3.7/site-packages/autoreject/autoreject.py", line 679, in fit
    verbose=self.verbose)
  File "/Users/ opt/anaconda3/envs/mne3/lib/python3.7/site-packages/autoreject/autoreject.py", line 444, in _compute_thresholds
    dots=dots, verbose=verbose)
  File "/Users/ opt/anaconda3/envs/mne3/lib/python3.7/site-packages/autoreject/utils.py", line 239, in _clean_by_interp
    desc=mesg, verbose=verbose)):
  File "/Users/ opt/anaconda3/envs/mne3/lib/python3.7/site-packages/autoreject/utils.py", line 183, in _pbar
    pbar = ProgressBar(iterable, mesg=desc, spinner=True)
  File "/Users/ opt/anaconda3/envs/mne3/lib/python3.7/site-packages/mne/utils/progressbar.py", line 73, in __init__
    disable=disable, **kwargs)
  File "/Users/ opt/anaconda3/envs/mne3/lib/python3.7/site-packages/mne/externals/tqdm/_tqdm/std.py", line 943, in __init__
    TqdmKeyError("Unknown argument(s): " + str(kwargs)))
mne.externals.tqdm._tqdm.std.TqdmKeyError: "Unknown argument(s): {'spinner': True}"

**Comment by sappelhoff** [comment]
>  or use the old version mne(like0.19)?

you need to use `mne==0.19` for now until the bug is fixed :-)

**Comment by elvisjade** [comment]
> > or use the old version mne(like0.19)?
> 
> you need to use `mne==0.19` for now until the bug is fixed :-)

Is there any way to use autoreject in mne 0.20?
Because mne 0.19 has some bug , so I have to use mne 0.20.

Is this a bug or Is it my operation error?

I want to  read_custom_montage and follow the tutorial (https://mne.tools/stable/auto_tutorials/source-modeling/plot_eeg_mri_coords.html?highlight=read_custom_montage)

I use this code :
import mne
from mne.channels import compute_native_head_t, read_custom_montage
from mne.viz import plot_alignment

dig_montage =read_custom_montage(lname,head_size=None)
dig_montage.plot()

It will work when I use mne 0.20, but I will report error when I use 0.19

(---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-e58d13d7a65c> in <module>
      7 from mne.preprocessing import (ICA, create_eog_epochs, create_ecg_epochs,
      8                                corrmap)
----> 9 from mne.channels import compute_native_head_t, read_custom_montage

ImportError: cannot import name 'compute_native_head_t' from 'mne.channels' (/Users/opt/anaconda3/envs/mne2/lib/python3.7/site-packages/mne/channels/__init__.py)

I want to use adjust plugin (https://699-59485140-gh.circle-artifacts.com/0/html/index.html#) but it have to use mne 0.19.

Is there any way to use  from mne.channels import compute_native_head_t, read_custom_montage in mne 0.19 or to use the code (dig_montage =read_custom_montage(lname,head_size=None)
dig_montage.plot()) in mne 0.19?

I have try to use from mne.channels import read_custom_montage in mne 0.19 . And then when I run the code(dig_montage =read_custom_montage(lname,head_size=None)) it will report a error(ValueError: Points have to be provided as one dimensional arrays of length 3.)
But it can run in mne 0.20.

**Comment by jasmainak** [comment]
@sappelhoff @agramfort or @dengemann can you please help? I opened a PR but it doesn't look like I'll be able to finish it at least for the coming week. I can't promise beers nowadays but I'll make a PR in exchange some day ... :)

**Comment by agramfort** [comment]
@elvisjade you can now user mne stable 0.20 and autoreject master thanks to https://github.com/autoreject/autoreject/pull/176

**Comment by elvisjade** [comment]
> @elvisjade you can now use mne stable 0.20 and autoreject master thanks to #176

Thank you very much！！！
