### ISSUE TITLE
Is there any tutorial on how to calculate  n_interpolates or consensus_percs?

### ISSUE THREAD

**Issue by elvisjade** [autoreject/autoreject#175]
In the tutorial:
Let us first define the parameters. n_interpolates are the 𝜌 values that we would like autoreject to try and consensus_percs are the 𝜅 values that autoreject will try (see the autoreject paper) for more information on these parameters).

Epochs with more than 𝜅∗𝑁 sensors (𝑁 total sensors) bad are dropped. For the rest of the epochs, the worst 𝜌 bad sensors (as determined by channel-level thresholds) are interpolated. The exact values of these parameters are not preselected but learned from the data. If the number of bad sensors for a particular trial is less than 𝜌, all the bad sensors are interpolated.

n_interpolates = np.array([1, 4, 32])
consensus_percs = np.linspace(0, 1.0, 11)

But after I read the paper, I still didn't understand how to calculate these variables. I don't know if it's because I don't have enough mathematical knowledge, or did I not understand? There is no obvious thing in the paper about how to calculate these variables。

Can someone help me? Thank you so much.

**Comment by jasmainak** [comment]
hi @elvisjade the `consensus_perc` can never be greater than 1. or smaller than 0., so we try 11 values from 0 to 1.0. You could try a denser grid but it would take longer.

As for `n_interpolates` it's the same logic. Note that this parameter is a bit more nuanced. If `n_interpolate` is 32, it does not mean you interpolate 32 channels. In fact, it simply means that 32 is the maximum number of channels you can interpolate.

Does that help?

**Comment by elvisjade** [comment]
> hi @elvisjade the `consensus_perc` can never be greater than 1. or smaller than 0., so we try 11 values from 0 to 1.0. You could try a denser grid but it would take longer.
> 
> As for `n_interpolates` it's the same logic. Note that this parameter is a bit more nuanced. If `n_interpolate` is 32, it does not mean you interpolate 32 channels. In fact, it simply means that 32 is the maximum number of channels you can interpolate.
> 
> Does that help?

Okay, thank you for your reply! I understand a little.

But I still have some questions, such as what does this value 4 in n_interpolates = np.array ([1, 4, 32]) represent?
In addition, if I have 128 channels, and then I choose 32, it is similar to ica. Will the most serious 32 be selected for repair? Or is it randomly selected 32? I see in the paper that it means the most serious Of 32?

The set of good trials Gkκ in the training set Tk can, therefore, be written mathematically as:
In the remaining trials, if ρ <κ, one needs to define what are the worse ρ sensors that shall be interpolated.
To do this we propose to rank the sensors for “badness” according to a score. A natural strategy to set the score is to use the peak-to-peak amplitude itself:
Higher the score sij, the worse is the sensor. The −∞ score is for ignoring the good sensors in the subsequent step. The following strategy is used for interpolation. If the number of bad sensors 􏰀Q C ′
j ′ = 1 ij is less than ρ we will interpolate all of them. Otherwise, we will interpolate the ρ sensors with the highest
scores. In other words, we interpolate at most min () sensors

And what does this try 11 values ​​from 0 to 1.0 mean? What does the function of consults_perc mean? I still don't understand.

**Comment by jasmainak** [comment]
>  I see in the paper that it means the most serious Of 32?

yes exactly

> And what does this try 11 values ​​from 0 to 1.0 mean?

it means you select the best K among the values 0, 0.1, 0.2, ..., 1.0 based on your data.

**Comment by elvisjade** [comment]
> > I see in the paper that it means the most serious Of 32?
> 
> yes exactly
> 
> > And what does this try 11 values ​​from 0 to 1.0 mean?
> 
> it means you select the best K among the values 0, 0.1, 0.2, ..., 1.0 based on your data.

and  What does the function of consults_perc mean? 

![image](https://user-images.githubusercontent.com/12797356/79407663-1d4f1780-7fcc-11ea-9ed7-d30eee52a841.png)

Does this variable refer to the threshold of the data? If the smaller, the more strict the data, the more epochs repaired?

**Comment by jasmainak** [comment]
no, consensus_perc is the κ

**Comment by elvisjade** [comment]
> no, consensus_perc is the κ

![image](https://user-images.githubusercontent.com/12797356/80050613-b5a74800-8548-11ea-9af0-22b3de9cb56b.png)

consensus_percs = np.linspace (0, 1.0, 11)
If this is K, then it seems to be the opposite of the threshold?
Does it mean that the closer k is to 0, the stricter the threshold? I tried 1, 0.8, 0.5 myself, it seems that the number of deleted epochs will gradually increase. I want to ask how to adjust the threshold.

**Comment by elvisjade** [comment]
I reread this paper about auto-reject and discussed it with my classmates.
We are now about
n_interpolates = np.array ([1, 4, 32])
consensus_percs = np.linspace (0, 1.0, 11)
The n_interpolates parameter seems to be more about patching channels.
32 represents the maximum number of channels that can be patched.
1,4 represents the worst repaired 1 or the worst repaired 1-n (such as the 4th)

The consensus_percs parameter is more about threshold control.Consensus_percs multiplied by n_interpolates will give a threshold τ.
This parameter consensus_percs is to select a few numbers from 0-1 or 0-n (such as selecting 10) and then use it as a parameter. Of course, you can also directly give a fixed value, but it is better and more suitable to use a machine to select the data itself.
Then the value obtained by multiplying this decimal by n_interpolates is the threshold. If an epoch is within this threshold, the broken channel is less than this threshold, then the epoch will be patched. If the broken channel in this epoch is greater than this threshold, then Will discard this epoch.
I want to ask if we understand these two parameters correctly?

**Comment by jasmainak** [comment]
hi @elvisjade I feel you are mixing up many concepts here. 

> Then the value obtained by multiplying this decimal by n_interpolates is the threshold. If an epoch is within this threshold, the broken channel is less than this threshold, then the epoch will be patched. If the broken channel in this epoch is greater than this threshold, then Will discard this epoch.

I don't follow this part. When you say "threshold", it's not clear what you refer to.

> If this is K, then it seems to be the opposite of the threshold?

you are looking at the wrong part of the paper. This is kappa, not K -- look at equation (6).

In any case, I'm afraid I can't help further. The purpose here for us is to help users use the software and to answer any data-related questions. This is a bit beyond that. I would suggest setting up a journal club to discuss and understand it. Good luck and happy auto-rejecting!

**Comment by elvisjade** [comment]
> hi @elvisjade I feel you are mixing up many concepts here.
> 
> > Then the value obtained by multiplying this decimal by n_interpolates is the threshold. If an epoch is within this threshold, the broken channel is less than this threshold, then the epoch will be patched. If the broken channel in this epoch is greater than this threshold, then Will discard this epoch.
> 
> I don't follow this part. When you say "threshold", it's not clear what you refer to.
> 
> > If this is K, then it seems to be the opposite of the threshold?
> 
> you are looking at the wrong part of the paper. This is kappa, not K -- look at equation (6).
> 
> In any case, I'm afraid I can't help further. The purpose here for us is to help users use the software and to answer any data-related questions. This is a bit beyond that. I would suggest setting up a journal club to discuss and understand it. Good luck and happy auto-rejecting!

Okay, I am very grateful for your reply and your help during this time. You really helped me a lot.

I'm sorry to ask you some other questions. There may be some questions that have nothing to do with the use of this package because I did not understand some parameters.

I will continue to look at this paper and then understand it further.

Thank you very much!
