### ISSUE TITLE
error:Valid channel positions are neededfor autoreject to work

### ISSUE THREAD

**Issue by Ann-KathrinKiessner** [autoreject/autoreject#179]
hi,

i‘ve been trying to use autoreject to clean up the raw data taken from the TUH Abnormal EEG Corpus (https://www.isip.piconepress.com/projects/tuh_eeg/html/downloads.shtml). I‘ve loaded the raw data and epoched it using mne.

ar = AutoReject()
epochs_clean = ar.fit_transform(epochs)
Now, I want to use autorejct on those eopchs, but doing so, I get the following error Valid channel positions are neededfor autoreject to work.

I‘ve already tried to add channel positions approximated for an 10_20, which were already used in the Braindecode tutorial (https://robintibor.github.io/braindecode/notebooks/visualization/Perturbation.html) to plot the data. 
However, this does not work either.

Any idea  why?
And why must  info["chs"][0]["loc"] be ndarray with 12 elements ?

Thank you. 

Best,
Ann-Kathrin

**Comment by agramfort** [comment]
>
> i‘ve been trying to use autoreject to clean up the raw data taken from the
> TUH Abnormal EEG Corpus (
> https://www.isip.piconepress.com/projects/tuh_eeg/html/downloads.shtml).
> I‘ve loaded the raw data and epoched it using mne.
>
> ar = AutoReject()
> epochs_clean = ar.fit_transform(epochs)
> Now, I want to use autorejct on those eopchs, but doing so, I get the
> following error Valid channel positions are neededfor autoreject to work.
>

did you set the channel locations using make_standard_montage and
set_montage  ?

> I‘ve already tried to add channel positions approximated for an 10_20,
> which were already used in the Braindecode tutorial (
> https://robintibor.github.io/braindecode/notebooks/visualization/Perturbation.html)
> to plot the data.
> However, this does not work either.
>
I don't see where locations are used in this code.


> Any idea why?
> And why must info["chs"][0]["loc"] be ndarray with 12 elements ?
>
it's because it can deal with more complex channels eg MEG coils. For EEG
only the first 3 numbers are used.

**Comment by AK-16** [comment]
> did you set the channel locations using make_standard_montage and set_montage ?
I've tried to set the the channel locations using make_standard_montage and
set_montage 

but I only get the following error:ValueError: DigMontage is a only a subset of info. There are 30 channel positions not present in the DigMontage. The required channels are: ['EEG FP1-REF', 'EEG FP2-REF', 'EEG F3-REF', 'EEG F4-REF', 'EEG C3-REF', 'EEG C4-REF', 'EEG P3-REF', 'EEG P4-REF', 'EEG O1-REF', 'EEG O2-REF', 'EEG F7-REF', 'EEG F8-REF', 'EEG T3-REF', 'EEG T4-REF', 'EEG T5-REF', 'EEG T6-REF', 'EEG A1-REF', 'EEG A2-REF', 'EEG FZ-REF', 'EEG CZ-REF', 'EEG PZ-REF', 'EEG ROC-REF', 'EEG LOC-REF', 'EEG EKG1-REF', 'EEG T1-REF', 'EEG T2-REF', 'PHOTIC-REF', 'IBI', 'BURSTS', 'SUPPR']

> I‘ve already tried to add channel positions approximated for an 10_20, which were already used in the Braindecode tutorial ( https://robintibor.github.io/braindecode/notebooks/visualization/Perturbation.html) to plot the data. However, this does not work either.
> I don't see where locations are used in this code.
I used the CHANNEL_10_20_APPROX imported from braindecode.datasets.sensor_positions

**Comment by agramfort** [comment]
you cannot expect autoreject to clean EEG data without channel locations.

you have to ignore/drop the channels for which you have no location.

>
