### ISSUE TITLE
TqdmKeyError: "Unknown argument(s): {'spinner': True}"

### ISSUE THREAD

**Issue by guishuyunye-lyw** [autoreject/autoreject#182]
I got this error again with  the MNE 0.20.7

**Comment by jasmainak** [comment]
are you using the development version of autoreject? If not, can you try with that?

**Comment by guishuyunye-lyw** [comment]
I tried, it works now, thx so much!

**Comment by jasmainak** [comment]
okay we'll need to make a release soon ...
