### ISSUE TITLE
epochs plot

### ISSUE THREAD

**Issue by guishuyunye-lyw** [autoreject/autoreject#184]
![image](https://user-images.githubusercontent.com/20347818/90351927-51b70b00-e074-11ea-85e5-5d5609ba5774.png)
How could I plot epochs like this. Everytime I want to check the epochs rejected, they were just disappeared.

**Comment by jasmainak** [comment]
what do you mean disappear? How do you plot them? Are you using ipython?

**Comment by guishuyunye-lyw** [comment]
> what do you mean disappear? How do you plot them? Are you using ipython?

yes, plot with epochs.plot()

**Comment by guishuyunye-lyw** [comment]
I thought this is the solution: http://autoreject.github.io/auto_examples/plot_visualize_bad_epochs.html#sphx-glr-auto-examples-plot-visualize-bad-epochs-py

**Comment by jasmainak** [comment]
okay great you managed to find the solution!
