### ISSUE TITLE
Some question about combining autoreject(local) with ICA.

### ISSUE THREAD

**Issue by guishuyunye-lyw** [autoreject/autoreject#185]
Dear autoreject team 

When I try to mimic the process provided on autoreject's FQA page, I got a question about the topic "Should I apply ICA first or autoreject first?"
 
To ignore bad segments using autoreject (local), we could do:
>>> ar = AutoReject()
>>> _, reject_log = ar.fit(epochs).transform(epochs, return_log=True)
>>> ica.fit(epochs[~reject_log.bad_epochs])

hi @SebastianSpeer @jasmainak @agramfort , after ica.fit(), ica.apply(),should I run fit_transform() again or just used what fited before? Could you guys give us an completed pattern?

**Comment by agramfort** [comment]
did you look at:
https://autoreject.github.io/faq.html#should-i-apply-ica-first-or-autoreject-first
 ?

>

**Comment by guishuyunye-lyw** [comment]
> did you look at: https://autoreject.github.io/faq.html#should-i-apply-ica-first-or-autoreject-first ?
> […](#)

Thx, I read it before. So I should do twice autorejects, before and after ICA process, then the parameters should be set the same?

**Comment by jasmainak** [comment]
closed by #221
