### ISSUE TITLE
TqdmKeyError: "Unknown argument(s): {'spinner': True}"

### ISSUE THREAD

**Issue by FilmonM** [autoreject/autoreject#190]
Hi everyone!
I found this package and really want to use it on EEG data but when I try to fit the autoreject function on my epochs, I get the following error: 

TqdmKeyError: "Unknown argument(s): {'spinner': True}"

Now, I'm not quite sure if the problem is from my EEG data or something else? I will attach a code example on this comment.

I would appreciate every input :)
![Pic1](https://user-images.githubusercontent.com/66641147/99603722-2c83c100-2a04-11eb-90ec-e8872b39c08b.jpg)
![pic2](https://user-images.githubusercontent.com/66641147/99603776-4e7d4380-2a04-11eb-9296-9c0a630e453f.jpg)
![pic3](https://user-images.githubusercontent.com/66641147/99603732-33123880-2a04-11eb-9460-97d1583e5d2e.jpg)
![pic4](https://user-images.githubusercontent.com/66641147/99603733-34436580-2a04-11eb-8fa1-90477e35d72d.jpg)

**Comment by jasmainak** [comment]
Can you try using the development version: 

```sh
$ pip install https://api.github.com/repos/autoreject/autoreject/zipball/master
```

**Comment by jmurphy88** [comment]
same issue for me. Tried Dev version, no difference

**Comment by jasmainak** [comment]
What version of MNE are you using? It works for me ...

**Comment by agerhardsson** [comment]
I get the same issue when running the example from the autoreject site. Running latest MNE 21.2. I get another issue when trying on my own data but will post that in a dedicated issue.

**Comment by agramfort** [comment]
what tqdm version are you using?

>

**Comment by agerhardsson** [comment]
I appreciate the quick reply! First, tqdm 4.41.1 then I updated to latest version 4.54.1, still same issue.

**Comment by agerhardsson** [comment]
It worked after setting verbose=False in AutoReject()

**Comment by jmurphy88** [comment]
> What version of MNE are you using? It works for me ...

Latest. Didn't update, but it has now started working for me, and I don't know why!

**Comment by agerhardsson** [comment]
Which tqdm version are you using? Still getting the same error.

**Comment by agerhardsson** [comment]
Problem seems to occur when verbose='progressbar' which I guess is default. Setting to verbose='tqdm' no works for me.

**Comment by jasmainak** [comment]
how can I reproduce? can you tell me your:

- MNE version
- autoreject version
- tqdm version

?

**Comment by agerhardsson** [comment]
Tried using the autoreject example script and data. 
MNE 0.21.2
autoreject 0.2.1
tqdm 4.54.1 (also tried 4.39.0 with same result)

**Comment by jasmainak** [comment]
But you did not try the development version as [I recommended above](https://github.com/autoreject/autoreject/issues/190#issuecomment-730080660) ? Please let me know if it fixes it. We will make a release soon so if it works then we're good.

**Comment by agerhardsson** [comment]
Updating to dev-version did the trick!

**Comment by jasmainak** [comment]
I just minted a new release. This issue should be gone now
