### ISSUE TITLE
index 308 is out of bounds for axis 0 with size 306

### ISSUE THREAD

**Issue by agerhardsson** [autoreject/autoreject#191]
Trying to fit autocorrect accordingly:

picks = mne.pick_types(epochs.info, meg='grad',  exclude=[])
ar = auto.AutoReject(picks)

epoch.info show the following channels,
chs : list | 354 items (EOG: 2, ECG: 1, IAS: 11, MAG: 102, GRAD: 204, MISC: 6, STIM: 18, SYST: 1, CHPI: 9)

and picks: 
array([ 15,  16,  18,  19,  21,  22,  24,  25,  27,  28,  30,  31,  33,
        34,  36,  37,  39,  40,  42,  43,  45,  46,  48,  49,  51,  52,
        54,  55,  57,  58,  60,  61,  63,  64,  66,  67,  69,  70,  72,
        73,  75,  76,  78,  79,  81,  82,  84,  85,  87,  88,  90,  91,
        93,  94,  96,  97,  99, 100, 102, 103, 105, 106, 108, 109, 111,
       112, 114, 115, 117, 118, 120, 121, 123, 124, 126, 127, 129, 130,
       132, 133, 135, 136, 138, 139, 141, 142, 144, 145, 147, 148, 150,
       151, 153, 154, 156, 157, 159, 160, 162, 163, 165, 166, 168, 169,
       171, 172, 174, 175, 177, 178, 180, 181, 183, 184, 186, 187, 189,
       190, 192, 193, 195, 196, 198, 199, 201, 202, 204, 205, 207, 208,
       210, 211, 213, 214, 216, 217, 219, 220, 222, 223, 225, 226, 228,
       229, 231, 232, 234, 235, 237, 238, 240, 241, 243, 244, 246, 247,
       249, 250, 252, 253, 255, 256, 258, 259, 261, 262, 264, 265, 267,
       268, 270, 271, 273, 274, 276, 277, 279, 280, 282, 283, 285, 286,
       288, 289, 291, 292, 294, 295, 297, 298, 300, 301, 303, 304, 306,
       307, 309, 310, 312, 313, 315, 316, 318, 319])

... I get the following error:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-17-fc7f05b06874> in <module>
----> 1 ar.fit(epochs)

~/anaconda3/lib/python3.7/site-packages/autoreject/autoreject.py in fit(self, epochs)
   1004                                      self.n_interpolate, self.cv_,
   1005                                      self.consensus, self.dots,
-> 1006                                      self.verbose)
   1007             self.threshes_.update(this_local_reject.threshes_)
   1008 

~/anaconda3/lib/python3.7/site-packages/autoreject/autoreject.py in _run_local_reject_cv(epochs, thresh_func, picks_, n_interpolate, cv, consensus, dots, verbose)
    761                                verbose=verbose, picks=picks_,
    762                                dots=dots)
--> 763     local_reject.fit(epochs)
    764 
    765     assert len(local_reject.consensus_) == 1  # works with one ch_type

~/anaconda3/lib/python3.7/site-packages/autoreject/autoreject.py in fit(self, epochs)
    677         self.threshes_ = self.thresh_func(
    678             epochs.copy(), dots=self.dots, picks=self.picks_,
--> 679             verbose=self.verbose)
    680 
    681         reject_log = self.get_reject_log(epochs=epochs, picks=self.picks_)

~/anaconda3/lib/python3.7/site-packages/autoreject/autoreject.py in _compute_thresholds(epochs, method, random_state, picks, augment, dots, verbose, n_jobs)
    442         if augment:
    443             epochs_interp = _clean_by_interp(epochs, picks=picks,
--> 444                                              dots=dots, verbose=verbose)
    445             # non-data channels will be duplicate
    446             data = np.concatenate((epochs.get_data(),

~/anaconda3/lib/python3.7/site-packages/autoreject/utils.py in _clean_by_interp(inst, picks, dots, verbose)
    243 
    244         interpolate_bads(inst, picks=picks, dots=dots,
--> 245                          reset_bads=True, mode='fast')
    246 
    247         if isinstance(inst, mne.Evoked):

~/anaconda3/lib/python3.7/site-packages/autoreject/utils.py in interpolate_bads(inst, picks, dots, reset_bads, mode)
    291     if len(meg_picks_interp) > 0:
    292         _interpolate_bads_meg_fast(inst, picks=meg_picks_interp,
--> 293                                    dots=dots, mode=mode)
    294 
    295     if reset_bads is True:

~/anaconda3/lib/python3.7/site-packages/autoreject/utils.py in _interpolate_bads_meg_fast(inst, picks, mode, dots, verbose)
    368     if len(inst.ch_names) > len(picks):
    369         picked_info = pick_info(inst.info, picks)
--> 370         dots = _pick_dots(dots, picks, picks)
    371         inst_picked = False
    372     else:

~/anaconda3/lib/python3.7/site-packages/autoreject/utils.py in _pick_dots(dots, pick_from, pick_to)
    438         return dots
    439     self_dots, cross_dots = dots
--> 440     self_dots = self_dots[pick_from, :][:, pick_from]
    441     cross_dots = cross_dots[pick_to, :][:, pick_from]
    442     return [self_dots, cross_dots]

IndexError: index 308 is out of bounds for axis 0 with size 306

**Comment by agramfort** [comment]
make sure the picks only contain the MEG channels

>

**Comment by agerhardsson** [comment]
They do. If not I would get another error message "AutoReject only supports mag, grad, and eeg at this point."

I don't know if it is the order of the channels, starting with EOG: 2, ECG: 1, IAS: 11?

So it seems as though pick_types selects the correct channels according to the epochs.info, but the AutoReject only accepts the order of the channels starting with MEG?

**Comment by agramfort** [comment]
can you share a dropbox folder with data and a script to replicate?

**Comment by jasmainak** [comment]
you might also want to read this related issue: https://github.com/autoreject/autoreject/issues/187. I'm not exactly sure how the user fixed it but you might get some inspiration

**Comment by agerhardsson** [comment]
issue: #187 seems to have been the same, although I'm not sure if I could resolve it. 

I tried to use pick only meg channels when creating the Epochs, and the initial error does not appear. However, the fit has been running for hours without apparent progress. Is this normal?

I resampled a 10 min snippet of data for testing:
https://stockholmuniversity.box.com/s/j47s66livxqpno5x619w4y8im2jfchw1

I have used the following code for debugging:

import mne  # version 0.21.2
import autoreject as auto  # version 0.2.1
file = 'data/emo_1-60Hz-raw.fif'

raw = mne.io.Raw(file, preload=True)

events = mne.find_events(raw, stim_channel=None,
                                         min_duration=0.02,
                                         verbose=True,
                                         uint_cast=True)
event_id = dict()

event_id['Cond1/Left'] = 85
event_id['Cond1/Right'] = 106
event_id['Cond2/Left'] = 89
event_id['Cond2/Right'] = 102
event_id['Cond3/Left'] = 86
event_id['Cond3/Right'] = 105
event_id['Cond4/Left'] = 90
event_id['Cond4/Right'] = 101

picks = mne.pick_types(raw.info, meg=True, exclude=[])

# This gives: IndexError: index 308 is out of bounds for axis 0 with size 306
# epochs = mne.Epochs(raw, events=events, event_id=event_id, preload=True)

# Adding picks for epochs does not produce an error directly, but process seems
# to be very slow, ran for a few hours without apparent progress.
epochs = mne.Epochs(raw, events=events, event_id=event_id, preload=True,
                    picks=picks)

# verbose = False: tqdm.std.TqdmKeyError: "Unknown argument(s): {'spinner': True}"
# dqdm version: 4.54.1
ar = auto.AutoReject(picks, verbose=False)

ar.fit(epochs)

**Comment by agramfort** [comment]
I am running your example on my machine and it runs fine for me.... can you
say what "mne.sys_info()" gives?

In [1]: %run test_autoreject.py
579 events found
Event IDs: [   1   85   86   89   90  101  102  105  106  149  150  153
 154  165
  166  169  170  256  257  357  512 4373 4374 4377 4378 4645 4646 4649
 4650 8486 8489]
Creating augmented epochs:
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|
102/102 [00:05<00:00, 17.69it/s]
Computing thresholds ...:
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|
102/102 [00:44<00:00,  2.31it/s]
Repairing epochs:
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|
131/131 [00:01<00:00, 90.50it/s]
Repairing epochs:
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|
131/131 [00:11<00:00, 11.91it/s]
Fold:
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|
10/10 [00:03<00:00,  2.81it/s]
Repairing epochs:
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|
131/131 [00:12<00:00, 10.79it/s]
Fold:
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|
10/10 [00:03<00:00,  2.90it/s]
Repairing epochs:
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|
131/131 [00:11<00:00, 11.42it/s]

>

**Comment by agerhardsson** [comment]
Running from different Platforms but this is after reinstalling a conda mne environment:

Platform:      macOS-10.15.7-x86_64-i386-64bit
Python:        3.8.6 | packaged by conda-forge | (default, Nov 27 2020, 19:17:44)  [Clang 11.0.0 ]
Executable:    /Users/ange3856/miniconda3/envs/mne/bin/python
CPU:           i386: 4 cores
Memory:        16.0 GB

mne:           0.21.2
numpy:         1.19.4 {blas=NO_ATLAS_INFO, lapack=lapack}
scipy:         1.5.3
matplotlib:    3.3.3 {backend=module://ipykernel.pylab.backend_inline}

sklearn:       0.23.2
numba:         0.52.0
nibabel:       3.2.1
cupy:          Not found
pandas:        1.1.5
dipy:          1.3.0
mayavi:        4.7.2
pyvista:       0.27.4 {pyvistaqt=0.2.0, OpenGL 4.1 INTEL-14.7.8 via Intel(R) Iris(TM) Graphics 6100}
vtk:           9.0.1
PyQt5:         5.12.3

**Comment by agramfort** [comment]
are you saying it works now with different platform?

>

**Comment by agerhardsson** [comment]
Still running, so too soon to tell.

**Comment by agerhardsson** [comment]
The script runs. But I have to define the picks when creating the epochs, not in AutoReject(). I also have to specify verbose='tqdm') to track progress, as the default 'progressbar' does not work. 

auto.AutoReject(verbose='tqdm') worked!

auto.AutoReject(picks=picks, verbose='tqdm'), produce the index error!

auto.AutoReject(picks, verbose='tqdm') was obviously wrong as I had picks defining the n_interpolates, hence the long run-time. 

Thanks for the help!
