### ISSUE TITLE
Cannot import autoreject

### ISSUE THREAD

**Issue by nithyar89** [autoreject/autoreject#195]
I use Python 3.7.4, MNE 0.21.0, and installed autoreject 0.2.1 https://pypi.org/project/autoreject/ 
ImportError: cannot import name '_layout_figure' from 'mne.viz.utils' (/usr/bin/anaconda2/lib/python3.7/site-packages/mne/viz/utils.py)

Looks like this is specific to my user environment in the server. 
>>> import autoreject
/usr/bin/anaconda2/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/nithya/.local/lib/python3.7/site-packages/autoreject/__init__.py", line 3, in <module>
    from .autoreject import _GlobalAutoReject, _AutoReject, AutoReject
  File "/home/nithya/.local/lib/python3.7/site-packages/autoreject/autoreject.py", line 27, in <module>
    from .viz import plot_epochs
  File "/home/nithya/.local/lib/python3.7/site-packages/autoreject/viz.py", line 20, in <module>
    from mne.viz.utils import (figure_nobar, _toggle_proj, _toggle_options,
ImportError: cannot import name '_layout_figure' from 'mne.viz.utils' (/usr/bin/anaconda2/lib/python3.7/site-packages/mne/viz/utils.py)

**Comment by jasmainak** [comment]
Can you try to install the latest development version of autoreject to see if it works?

```py
$ pip install https://api.github.com/repos/autoreject/autoreject/zipball/master
```

**Comment by jasmainak** [comment]
was the problem solved?

**Comment by jasmainak** [comment]
closing due to no response from OP
