### ISSUE TITLE
Set KFold(..., shuffle=True) in get_rejection_threshold

### ISSUE THREAD

**Issue by msseibel** [autoreject/autoreject#196]
When using the global rejection function I found that always the same splitting is used.

I suppose it should not be:
https://github.com/autoreject/autoreject/blob/dd0942438440070876e8ea4796b83ffdd4981600/autoreject/autoreject.py#L219

but rather: 
`cv = KFold(n_splits=cv, random_state=random_state,shuffle=True)`
or
`cv = KFold(n_splits=cv, random_state=random_state,shuffle=shuffle)`
and shuffle can be set as a param.

In fact it makes to call `get_rejection_threshold` repeatedly in order to get a better threshold, since the returned threshold varies when shuffle=True.

**Comment by jasmainak** [comment]
can you explain why shuffling is necessary? I don't quite follow ...

**Comment by msseibel** [comment]
I am using the method for continuous resting state MEG data. So I needed to chunk the continuous data into epochs. I decided to use a duration of 1 sec with an overlap of 0.5 sec. Now it comes that consecutive epochs contain similar peak to peak values. (I suppose the trials are temporally correlated, especially the artifacts in my signals are sometimes longer than a few seconds). 
Maybe this example is the correct way to describe it:
Assume n_split=5 and the first 80% of the signal is good and the last 20% is bad. Then (without shuffling) there will be one validation fold that has only bad epochs (I guess that corrupts the estimate of the median). If shuffling=True then these bad trials can be uniformly distributed in all folds and it is more likely that the median selects trials that lie in the middle of the distribution. 
In the paper it was written, that the validation set should not contain only good trials, but isn't it the better when the validation set contains the true ratio of bad and good trials?

**Comment by jasmainak** [comment]
okay I see, your use case seems like a special case. I think ideally we want to allow the user to pass a `cv` instance. Something like:

```py
if cv is None:
    cv = KFold(n_splits=5, random_state=random_state) 
```

and then make `cv=None` the default in the function. How good are your github skills? Do you want to try making a pull request with the bugfix?

**Comment by msseibel** [comment]
Would be my first pull request. But I guess this is a good time to learn it.

**Comment by jasmainak** [comment]
looking forward to it!
