### ISSUE TITLE
[DOC] typo

### ISSUE THREAD

**Issue by nbara** [autoreject/autoreject#20]
Hi, just looking at the documentation of `LocalAutoRejectCV()`, and there seems to be a mixup:

![screen shot 2016-12-16 at 11 00 38](https://cloud.githubusercontent.com/assets/10333715/21258810/043a4948-c37f-11e6-85ad-08307180d0b7.png)

The defaults of `consensus_percs` and `n_interpolates` are switched (only in the description, the code looks fine)

**Comment by jasmainak** [comment]
Thanks a lot @nbara for reporting this! It's now fixed with [this commit](https://github.com/autoreject/autoreject/commit/5f484625f05f7fce7d836f226364b60bcecc8656)
