### ISSUE TITLE
Example downloads massive amount of data: Needs rework

### ISSUE THREAD

**Issue by sappelhoff** [autoreject/autoreject#201]
See:

https://github.com/autoreject/autoreject/blob/abddce733539e6c53c71e84e7bcbfa6e214281dc/examples/plot_visualize_bad_epochs.py#L26-L42

and as @agramfort says in https://github.com/autoreject/autoreject/pull/194#issuecomment-802301434:

> we download all the runs (SSS and raw) including fMRI and MRI....
> we should just fetch a couple of SSS files...

Perhaps using https://github.com/hoechenberger/openneuro-py (adding it as an optional dependency for docs)

**Comment by hoechenberger** [comment]
Sounds good, ping me please if you don't hear back from me ;)

**Comment by sappelhoff** [comment]
closed by https://github.com/autoreject/autoreject/pull/202
