### ISSUE TITLE
Can't set a random_state in get_rejection_threshold

### ISSUE THREAD

**Issue by adswa** [autoreject/autoreject#210]
Hi, thanks for maintaining this package.
Parametrizing ``get_rejection_threshold`` with the ``random_state`` parameter results in an internal error of sklearn. Here is a reproducer:

```python
import os
import mne
from autoreject import get_rejection_threshold
sample_data_folder = mne.datasets.sample.data_path()
sample_data_raw_file = os.path.join(sample_data_folder, 'MEG', 'sample', 'sample_audvis_raw.fif')
raw = mne.io.read_raw_fif(sample_data_raw_file)

tstep = 1.0
tmpevents = mne.make_fixed_length_events(raw, duration=tstep)
tmpepochs = mne.Epochs(raw, tmpevents, tmin=0.0,  tmax=tstep,  baseline=None, picks='meg')
reject = get_rejection_threshold(tmpepochs, random_state=42)
```

With ``autoreject=0.2.2`` and ``scikit-learn==0.24.1``, this results in

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-cfd0257bbf91> in <module>
      8                        baseline=None,
      9                        picks='meg')
---> 10 reject = get_rejection_threshold(tmpepochs, random_state=42)

~/env/magma/lib/python3.9/site-packages/autoreject/autoreject.py in get_rejection_threshold(epochs, decim, random_state, ch_types, cv, verbose)
    217         epochs.decimate(decim=decim)
    218 
--> 219     cv = KFold(n_splits=cv, random_state=random_state)
    220     for ch_type in ch_types:
    221         if ch_type not in epochs:

~/env/magma/lib/python3.9/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     61             extra_args = len(args) - len(all_args)
     62             if extra_args <= 0:
---> 63                 return f(*args, **kwargs)
     64 
     65             # extra_args > 0

~/env/magma/lib/python3.9/site-packages/sklearn/model_selection/_split.py in __init__(self, n_splits, shuffle, random_state)
    426     def __init__(self, n_splits=5, *, shuffle=False,
    427                  random_state=None):
--> 428         super().__init__(n_splits=n_splits, shuffle=shuffle,
    429                          random_state=random_state)
    430 

~/env/magma/lib/python3.9/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     61             extra_args = len(args) - len(all_args)
     62             if extra_args <= 0:
---> 63                 return f(*args, **kwargs)
     64 
     65             # extra_args > 0

~/env/magma/lib/python3.9/site-packages/sklearn/model_selection/_split.py in __init__(self, n_splits, shuffle, random_state)
    288 
    289         if not shuffle and random_state is not None:  # None is the default
--> 290             raise ValueError(
    291                 'Setting a random_state has no effect since shuffle is '
    292                 'False. You should leave '

ValueError: Setting a random_state has no effect since shuffle is False. You should leave random_state to its default (None), or set shuffle=True.
```

As far as I can see, there is no way to pass ``shuffle=True`` via ``get_rejection_threshold``.

**Comment by agramfort** [comment]
you need to set your own cv object to be able to do this I think.

**Comment by adswa** [comment]
> you need to set your own cv object to be able to do this I think.

Is this what #197 brings into the next release?

**Comment by agramfort** [comment]
exactly. You can now pass your own cv parameter

such as

cv=KFold(n_splits=5, shuffle=True, random_state=42)

in the function call

>

**Comment by adswa** [comment]
cool, thanks!

**Comment by kalenkovich** [comment]
@adswa, I have the same problem. In the current version of `autoreject`, when `get_rejection_threshold` sets up cross-validation [here](https://github.com/autoreject/autoreject/blob/f778daf17649a256b7ef06505d7d88eb850acc1f/autoreject/autoreject.py#L219), it uses the `random_state` parameter:

```python
cv = KFold(n_splits=cv, random_state=random_state)
```

Since there is nothing random about cross-validation, setting `random_state` does not hurt but does not really do anything either. `sklearn` started to warn about this in [`0.23`](https://github.com/scikit-learn/scikit-learn/commit/7effc37174ff82e2252a7f4ff442a2bc7562ea0b) and now, in [`0.24`](https://github.com/scikit-learn/scikit-learn/commit/ac8cbb3799bdfa31360c87bf1097410326dba0bd), it raises an error.

I think that downgrading `sklearn` to 0.23 should help but I haven't tried it myself yet.

**Comment by hoechenberger** [comment]
> Since there is nothing random about cross-validation, setting `random_state` does not hurt but does not really do anything either

Correct, by default, `KFold` doesn't do any shuffling. If you want that, instantiate `KFold` manually and pass the instance, as suggested by @agramfort above.

**Comment by kalenkovich** [comment]
> > Since there is nothing random about cross-validation, setting `random_state` does not hurt but does not really do anything either
> 
> Correct, by default, `KFold` doesn't do any shuffling. If you want that, instantiate `KFold` manually and pass the instance to `autoreject`, as suggested by @agramfort above.

I don't actually want the shuffling. I don't think OP is aiming for that either judging from their snippet.

The current version of `autoreject` does not work against `sklearn 0.24` if you supply `random_state` to `get_rejection_threshold`. 

The development version does not have this problem, but downgrading to `0.23` should work until it is released.

**Comment by hoechenberger** [comment]
> The current version of `autoreject` does not work against `sklearn 0.24` if you supply `random_state` to `get_rejection_threshold`.
> 
> The development version does not have this problem, but downgrading to `0.23` should work until it is released.

Oh, I see, sorry, I totally misunderstood the question / problem then! 🙈
