### ISSUE TITLE
Inconsistency in autoreject docs?

### ISSUE THREAD

**Issue by eduvalero** [autoreject/autoreject#229]
Hi, in the first code cell of the [FAQ section](https://autoreject.github.io/faq.html) of the docs, it is recommended to do the following:
```
reject = get_rejection_threshold(epochs)
ica.fit(epochs, reject=reject)
```
However, in the [MNE documentation](https://mne.tools/stable/generated/mne.preprocessing.ICA.html?highlight=ica%20fit#mne.preprocessing.ICA.fit), regarding the `reject` parameter of `ICA.fit`, it is explicitly said  that "It only applies if inst is of type Raw.". Thus, the recommendation above would not yield what intended. Can someone clear this up?

**Comment by hoechenberger** [comment]
This is an excellent catch and should definitely be corrected. We should agree upon a good practice here and then update the docs. Care to give it a shot?

**Comment by eduvalero** [comment]
I would personally update the autoreject docs. 

Instead of:
```
reject = get_rejection_threshold(epochs)
ica.fit(epochs, reject=reject)

```
I would do:
```
reject = get_rejection_threshold(epochs)
epochs.drop_bad(reject)
ica.fit(epochs)
```

This way the bad epochs found by `get_rejection_threshold` are dropped before `ica` comes in. Other suggestions are welcome.

**Comment by jasmainak** [comment]
@eduvalero did you see this: https://890-59485140-gh.circle-artifacts.com/0/html/auto_examples/plot_autoreject_workflow.html#sphx-glr-auto-examples-plot-autoreject-workflow-py

If this answers your questions, we might want to nuke that section in the FAQ and instead point them to the tutorial

**Comment by eduvalero** [comment]
Hi @jasmainak.

I have a question regarding the tutorial you linked. At the top, it says: 

> We recommend that you first highpass filter the data, then estimate the global rejection threshold and supply it to the ICA algorithm for a robust fit, and finally run autoreject (local).

However, if we group the code used to process the epochs in the tutorial, we get:
```
ar = autoreject.AutoReject(n_interpolate=[1, 2, 3, 4], random_state=11, n_jobs=1, verbose=True)
ar.fit(epochs[:20])  
epochs_ar, reject_log = ar.transform(epochs, return_log=True)

# compute ICA
ica = mne.preprocessing.ICA(random_state=99)
ica.fit(epochs[~reject_log.bad_epochs])

# compute channel-level rejections
ar = autoreject.AutoReject(n_interpolate=[1, 2, 3, 4], random_state=11, n_jobs=1, verbose=True)
ar.fit(epochs[:20]) 
epochs_ar, reject_log = ar.transform(epochs, return_log=True)
epochs[reject_log.bad_epochs].plot(scalings=dict(eeg=100e-6))
```

From this code, I get the impression we are not applying: _autoreject (global) + ICA + autoreject (local)_
as indicated at the top of the tutorial, but _autoreject (local) + ICA + autoreject (local)_. Can you clear this up for me? Thanks.

**Comment by jasmainak** [comment]
Indeed, you should run "autoreject (local) + ICA + autoreject (local)". We should fix this in the tutorial. Thanks for bringing this up!

**Comment by eduvalero** [comment]
Then, I think if you fix that in the tutorial, you can get rid of the FAQ section. The example you shared already provides an explanation to the autoreject + ICA problem. Thank you!
