### ISSUE TITLE
Loading saved AutoReject objects

### ISSUE THREAD

**Issue by c-torre** [autoreject/autoreject#236]
Hi, I fitted many AutoReject objects in a long batch job and saved them with the `AutoReject.save` method. Thus, I got a bunch of `.h5` files, but I don't seem to find how to load them.

1. What would be the way to do this right now?
2. In any case, should there be a dedicated function do achieve this? For example `autoreject.load_autoreject` consistent with e.g. `mne.preprocessing.load_ica`.

Thanks!

**Comment by agramfort** [comment]
there is a read_auto_reject function in autoreject

it's not well documented though

>

**Comment by jasmainak** [comment]
closed by #237
