### ISSUE TITLE
Utility functions for autoreject

### ISSUE THREAD

**Issue by paulsowman** [autoreject/autoreject#244]
Hi, thanks for making autoreject. A great tool.

It seems there might be a problem with utils.py

the Function _compute_dots calls _setup_dots(mode, coils, 'meg'). This function (now?) seems to require an extra argument.

By changing:

Ln 426 to

    int_rad, noise, lut_fun, n_fact = _setup_dots(mode, info, coils, 'meg')

AND 

Ln 462 change to 

    int_rad, noise, lut_fun, n_fact = _setup_dots(mode, info_from, coils_from, 'meg')

I.e. adding in the 'info' argument, it seems to work. I'm not sure if this is correct though.

Kind regards, Paul

**Comment by jasmainak** [comment]
Can you do:

```sh
$ pip install https://api.github.com/repos/autoreject/autoreject/zipball/master
```

so you use the latest development version for now. I'll try to get a release out in the coming week

**Comment by sappelhoff** [comment]
> so you use the latest development version for now. I'll try to get a release out in the coming week

will be tracked in #252
