### ISSUE TITLE
Clarifying bad_epochs_idx arg in plot_epochs

### ISSUE THREAD

**Issue by cmoutard** [autoreject/autoreject#25]
Trying to use bad_epochs_idx argument in viz.plot_epochs, @giuliagennari and I got an issue.

Indeed, because of the line 182 :
```
epochs.drop_bad()
```
everything is built on a 'cleaner' subset of epochs.

Notably lines 317-318:
```
for color_idx in range(len(type_colors)):
    colors.append([type_colors[color_idx]] * len(epochs.events))
```
colors (later added to params) is a nested list of size len(ch_names) *  len(epochs.events), the latter dimension being related to the 'cleaner' subset of epochs.

However, lines 434-439 we loop over the bad_epochs_idx in params['colors'][ch_names][epochs_idx]:
```
for epoch_idx in params['bads']:
    params['ax_hscroll'].patches[epoch_idx].set_color((1., 0., 0., 1.))
    params['ax_hscroll'].patches[epoch_idx].set_zorder(3)
    params['ax_hscroll'].patches[epoch_idx].set_edgecolor('w')
    for ch_idx in range(len(params['ch_names'])):
        params['colors'][ch_idx][epoch_idx] = (1., 0., 0., 1.)
```
what may exceed the highest index of the 'cleaner' subset of epochs (e.g. if one of the bad epochs to display is the last one of the intial epochs object before drop_bad).

So I am not sure to understand, given the code, what is the aim of bad_epochs_idx argument in conjonction with the call to drop_bad. 
The two do not seem compatible IMHO (not considering the case of users having to anticipate the new indices in the 'cleaner' epochs subset of potentially bad epochs which are not rejected by drop_bad...).

**Comment by jasmainak** [comment]
Hey @cmoutard , in MNE you cannot take the `len(epochs)` unless you have done `epochs.drop_bad()`. At the moment, the onus is on the user to make sure they use `reject=None` when they construct epochs. So, the only purpose of `epochs.drop_bad()` is to allow taking the `len()`. It should not change the number of epochs. Maybe we should have a check to make sure `reject=None` before calling `epochs.drop_bad()` ...

**Comment by cmoutard** [comment]
Ok, much clearer now, thX a lot !

**Comment by jasmainak** [comment]
@cmoutard closing issue via https://github.com/autoreject/autoreject/commit/0c963393513525f5c376150ac1e4c12f95fcbb66. Added some more explicit error messages. Thanks for reporting it!
