### ISSUE TITLE
New stable release

### ISSUE THREAD

**Issue by eort** [autoreject/autoreject#252]
Hi everyone, 

Given that the current "stable" release (0.2.2) does not work in combination with MNE 0.24, would it make sense to pack a new release? Or make a note in the installation instructions that the stable version currently only runs with 0.23. (I just found out the hard way ;)

**Comment by sappelhoff** [comment]
+1

I think @jasmainak wanted to release soon, probably just hasn't got to it yet.

**Comment by jasmainak** [comment]
apologies! I need #253 to make the release and after that it will be done!

**Comment by jasmainak** [comment]
Just pushed to Pypi: https://pypi.org/project/autoreject/0.3/

happy new year :)

**Comment by jasmainak** [comment]
@sappelhoff I just realized there is a `conda` release for autoreject as well, thanks to you :) Do you have time to update it for the new release?

**Comment by sappelhoff** [comment]
Sure! But currently only @hoechenberger has admin rights, so I suggest he adds you and me first :-)

Happy new year!
