### ISSUE TITLE
How to set data-type and what's the precision autoreject uses?

### ISSUE THREAD

**Issue by binarycache** [autoreject/autoreject#257]
Hi,

Is there any way to enforce the data-type to 64-bit since I believe sci-kit learn uses Float32. Also let me know if it doesn't matter at all for rejecting epochs since it does in filtering and other steps?

Thank you.

**Comment by jasmainak** [comment]
hi @binarycache the data in MNE is all 64-bit except when saving if I remember correctly. See this old documentation:

https://mne.tools/0.14/manual/pitfalls.html#float64-vs-float32

I can't find it in the new docs. I don't think it should have a big impact on your results, so just use whatever MNE gives you
