### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by hoechenberger** [autoreject/autoreject#262]
Hello, have you considered cutting a new release to be compatible with the very-soon-to-be-released MNE-Python 1.0?

**Comment by jasmainak** [comment]
yes I owe this to @agramfort ;-) Perhaps first it's worth checking first if something breaks ... 

is there going to be a release candidate first or directly 1.0 ?

**Comment by jasmainak** [comment]
Done, made the new release :)

**Comment by hoechenberger** [comment]
Awesome, thank you!

**Comment by hoechenberger** [comment]
@jasmainak Can you please push an sdist to PyPI? There's only a wheel, which I cannot package for conda-forge. Thank you!

**Comment by sappelhoff** [comment]
perhaps automating the pypi pushing when making a GitHub release would be a smart thing? I do that in several repos and have not run into any issues: https://github.com/bids-standard/pybv/blob/main/.github/workflows/python_publish.yml

**Comment by hoechenberger** [comment]
> perhaps automating the pypi pushing when making a GitHub release would be a smart thing? I do that in several repos and have not run into any issues: https://github.com/bids-standard/pybv/blob/main/.github/workflows/python_publish.yml

Yep I do that too with `openneuro-py` and it's extremely convenient.

**Comment by hoechenberger** [comment]
> I just handed in my dissertation three days ago, so I am free again 🎉

CONGRATS!!!!!

**Comment by hoechenberger** [comment]
> store the PyPI credentials in GitHub settings

Be sure to switch to using tokens if you haven't done so already :)

**Comment by sappelhoff** [comment]
> CONGRATS!!!!!

thanks!

> Be sure to switch to using tokens if you haven't done so already :)

true! I actually use "upload tokens" for this GH action, not passwords.

**Comment by larsoner** [comment]
There is only one maintainer listed for the `autoreject` project on PyPi, which is also dangerous. @jasmainak could you add at least @agramfort and maybe @hoechenberger and me (Eric89GXL)? Then any one of us could push the `sdist` as well.

**Comment by larsoner** [comment]
> ALSO: I see that we still need the 0.3.1 GitHub release and the docs push. If you give me the rights, I can do that. I just handed in my dissertation three days ago, so I am free again ￼

I went to try to do this (not sure if I even have the permissions) but it looks like the `__init__.py` version is still 0.3, too. So make sure you (all) update that before doing a GitHub release and sdist PyPi upload:

https://github.com/autoreject/autoreject/blob/9cccda6c7617f4188da6269082d58191777586c8/autoreject/__init__.py#L2

**Comment by jasmainak** [comment]
> ALSO: I see that we still need the 0.3.1 GitHub release and the docs push. If you give me the rights, I can do that. I just handed in my dissertation three days ago, so I am free again 🎉

Congrats Dr. Appelhoff ! I don't think there should be a doc push because this is more like a backport release. There have been only 4 commits since 0.3. I'm not looking to do regular releases of autoreject ... MNE releases break autoreject because autoreject uses internals of MNE and the releases are to keep autoreject functioning.

> There is only one maintainer listed for the autoreject project on PyPi, which is also dangerous.

agree, I'll add @sappelhoff and @agramfort. But please ask me before making a release

and github pipeline sounds like a good idea! Not sure about poetry ... will wait until a few projects adapt it :)

**Comment by hoechenberger** [comment]
Re poetry, I haven't seen new projects in a while that do not use it instead of setup.py. But I do see your point. I will try to convince you to switch next year 😅😅😅

**Comment by hoechenberger** [comment]
Since autoreject uses MNE internals, I'm wondering if it could make sense to set up a regular (weekly) CI run to catch problems early? WDYT?

**Comment by larsoner** [comment]
I set up a `azure-pipelines.yml` for MNE-KIT-GUI that runs every night and emails when something breaks. Other than some false alarms due to Conda being too slow sometimes (which is mostly `mayavi`'s fault and I've fixed using `mamba`), it has been useful for this:

https://github.com/mne-tools/mne-kit-gui/blob/main/azure-pipelines.yml

I could set up something similar here if it would help. I assume @jasmainak should get an email, anyone else?

**Comment by larsoner** [comment]
... a maintainer would also either have to install the Azure app on GitHub if it's not already there, or give me maintainer or owner (not sure which) permissions to install it myself. There might be other admin stuff, too, but we can figure that out as we go.

**Comment by hoechenberger** [comment]
@larsoner I understand that it would be straightforward for you to re-use the existing Azure pipelines config, but wouldn't it be "easier" to use GH actions, in the sense that more maintainers would be familiar with it? Just a thought!

**Comment by hoechenberger** [comment]
We have something set up with `mne-bids`. Mind the `cron` trigger:

https://github.com/mne-tools/mne-bids/blob/abe93a3ba981e1805690532b6948f8dcd695cef1/.github/workflows/unit_tests.yml#L7-L16

I'm not sure if this sends out email notifications on failing tests, though.

**Comment by larsoner** [comment]
> We have something set up with mne-bids. Mind the cron trigger:

Yes, and CircleCI and Travis have something similar...

> I'm not sure if this sends out email notifications on failing tests, though.

... indeed this is the part that needs investigating, if you or someone else wants to investigate

**Comment by hoechenberger** [comment]
> Notifications for scheduled workflows are sent to the user who initially created the workflow. If a different user updates the cron syntax in the workflow file, subsequent notifications will be sent to that user instead. If a scheduled workflow is disabled and then re-enabled, notifications will be sent to the user who re-enabled the workflow rather than the user who last modified the cron syntax.

https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs

So this is probably not really what we want, right?

**Comment by larsoner** [comment]
> So this is probably not really what we want, right?

Correct. In Azure you can manually set/manage a list of emails to notify on run failure.

**Comment by hoechenberger** [comment]
Go ahead with Azure then 😁

**Comment by larsoner** [comment]
Hah!
```
VS850036: Maximum number of organizations reached.
```
@hoechenberger can you create the `autoreject` org on https://aex.dev.azure.com/me (there should be a big "Create new organization" button in the upper right once you sign in) then add me and Mainak as owners?

**Comment by hoechenberger** [comment]
@larsoner Not sure if I did this correctly, can you LMK if you've go sufficient permissions?

**Comment by jasmainak** [comment]
> if it's just about "too much work", I can commit to doing this. If there's another reason, what would it be?

mainly :) I will accept your offer ;-)

**Comment by larsoner** [comment]
```
401 - Uh-oh, you do not have access.
Your account, <snip>@gmail.com is not authorized to view this page.
```
It has my correct email listed but I can't see the org page. :( Did you add me as an owner?

When I refreshed it came to a page that said I should create a project, but then said:
```
You do not have sufficient permissions to create a new project. Please contact the organization administrator for support.
```
Not sure what's going on...

**Comment by jasmainak** [comment]
Yep, I did add you as "owner" ...

**Comment by jasmainak** [comment]
![image](https://user-images.githubusercontent.com/15852194/158468749-8a0877cc-0898-4f88-859a-a5be99312c75.png)

**Comment by larsoner** [comment]
Sorry, that comment was meant for @hoechenberger . I can add Azure using GitHub, but so far lack permissions on the Microsoft end for the autoreject org that @hoechenberger set up.

**Comment by hoechenberger** [comment]
I think you should be owner now

**Comment by hoechenberger** [comment]
The org apparently can only have a single owner

**Comment by larsoner** [comment]
Can you add me as an admin / highest non-owner permissions?

**Comment by larsoner** [comment]
Looks like I can create a project!

**Comment by larsoner** [comment]
... but only a private one. Perhaps you made a private org or something? In any case, if you can create a *public* `autoreject` project, I think I can proceed...

**Comment by hoechenberger** [comment]
@larsoner I actually had transferred ownership of the entire **org** to you … let's see if I can even change anything about the org now anymore!

**Comment by hoechenberger** [comment]
@larsoner never mind, I just saw https://github.com/autoreject/autoreject/pull/263#issuecomment-1068503736
so things appear to be working now as intended!

**Comment by larsoner** [comment]
Indeed, Azure is in process... now we "just" need @sappelhoff to work some automated release magic for more maintainability gains :)

**Comment by hoechenberger** [comment]
I already see his pain materialize b/c he'll have to do it on Azure now instead on GH Actions 😶‍🌫️

**Comment by larsoner** [comment]
Why? I didn't remove any GH action functionality, just added Azure...

**Comment by sappelhoff** [comment]
I think I have most of the rights I need now:

- pypi "maintainer"
- autoreject "write" (as far as I can tell)

I just need to be made collaborator on https://github.com/autoreject/autoreject.github.io so that I can push stable doc releases there. I got Mainak's approval here: https://github.com/autoreject/autoreject/issues/262#issuecomment-1068446039

:-)

**Comment by larsoner** [comment]
> pypi "maintainer"

You are listed here

https://pypi.org/project/autoreject/

> autoreject "write" (as far as I can tell)

I can take care of these now...

**Comment by larsoner** [comment]
Okay you have "maintainer" level for both repos: https://github.com/orgs/autoreject/teams/maintainers/repositories

Let me know if it's not sufficient and I'll rename the group and set perms to "Admin" level

**Comment by hoechenberger** [comment]
> Why? I didn't remove any GH action functionality, just added Azure...

Ah, got it!

**Comment by sappelhoff** [comment]
Great, I'll get to work tomorrow. Practically speaking, the 0.3.1 release will now always show 0.3.0 as its `__version__`, right? All I can do is upload an additional sdist to the wheel on pypi

**Comment by jasmainak** [comment]
what I did was update `__version__` in `maint/0.3.1` and create the dist on that branch without touching `master`. I think `__version__` in master should be `0.3.dev0`

**Comment by agramfort** [comment]
if you branch 0.3 then master should become 0.4.dev0
and 0.3.1 should be a bug fix release in the maint/0.3 branch

do you allow me to do this?

**Comment by hoechenberger** [comment]
> if you branch 0.3 then master should become 0.4.dev0 and 0.3.1 should be a bug fix release in the maint/0.3 branch

+1

**Comment by sappelhoff** [comment]
Okay, I'll not do anything for now then until I get green light from Alex that he is done 👍 I think we got green light from Mainak already, see above

**Comment by agramfort** [comment]
I started my day of meetings. Please give it a try. Otherwise it will wait
a bit

**Comment by sappelhoff** [comment]
> Let me know if it's not sufficient and I'll rename the group and set perms to "Admin" level

@larsoner it seems like I cannot set GitHub Secrets with my current permission - however I need to do that to add the PyPI upload token for automating the release push

**Comment by larsoner** [comment]
You should have admin permissions now for secrets

**Comment by sappelhoff** [comment]
What are your opinions on the "sleeping dogs"?

**Comment by hoechenberger** [comment]
Can we simply remove the respective tag?

**Comment by larsoner** [comment]
+1 for deleting 0.10 from GitHub and PyPi. It seems like the easiest solution. If someone *really* wants 0.1 or it's important to have it, we can go back to the right place in history and recreate the tag and push...

**Comment by sappelhoff** [comment]
fun story: on PyPI it's 0.1 :) so I think it was just a GitHub typo https://pypi.org/project/autoreject/0.1/

so we could:
- tag the commit that is currently tagged with v0.10 with another tag called v0.1
- delete the v0.10 tag AND associated release
- make a new v0.1 release based on the new v0.1 tag
- leave pypi as is

what about the 0.2.2 issue?

**Comment by hoechenberger** [comment]
Honestly I would just kill the 0.10 tag and not bother with the other stuff

**Comment by larsoner** [comment]
Agreed -- I also wouldn't worry about the 0.2.2 stuff but if you're really motivated to fix the tags, I don't see a problem with deleting the old bad ones and using the correct naming/numbers

**Comment by sappelhoff** [comment]
okay done - tags and releases are all in order now. The final issue is that the branch "maint/0.2.2" exists, which should rather be a commit in "maint/0.2" ... but I am not going to touch that, because it's too easy to screw something up there unnecessarily. :innocent:

**Comment by jasmainak** [comment]
Big thank you @sappelhoff !! 🥳 🙏 🚀 🧠
