### ISSUE TITLE
[ENH] Make exclusion of bad epochs optional

### ISSUE THREAD

**Issue by eort** [autoreject/autoreject#271]
Hi, 

In my pipeline, I usually prefer to not drop any epochs, but rather mark them as bad by changing the event code. Like that it is easier to match the behavioral file with the epochs. At the moment, I don't see a direct way of accomplishing this with autoreject while also doing the interpolation. I managed to workaround this by extracting the exclusion from the fitted RejectLog, and then call the private function `_apply_interp`. It works, but it is a little hacky. Would it make sense to add an option to `transform` that indicates whether the bad epochs are dropped or only their indices returned?

**Comment by sappelhoff** [comment]
Have you looked at https://mne.tools/dev/auto_tutorials/epochs/30_epochs_metadata.html ? You can attach the behavior data directly to `Epochs`, and whenever a particular epoch is dropped, the corresponding row from the (behavior) metadata is dropped as well.

**Comment by eort** [comment]
I wasn't aware of it actually! Thanks for pointing it out, this looks very useful. 

Still, I think there are situations in which optional dropping could be useful (e.g. compare bad/good epoch visually, manual adjustment of bads, etc.).

**Comment by jasmainak** [comment]
you can get the indices by doing `ar.get_reject_log(epochs)` which should contain the bad epoch indices in `reject_log.bad_epochs`. Regarding optional dropping capabilities I'm thinking of adding `epochs.transform(reject_log=reject_log)` that allows you to modify the automatic annotations based on visual inspection.

**Comment by eort** [comment]
>  I'm thinking of adding epochs.transform(reject_log=reject_log) that allows you to modify the automatic annotations based on visual inspection.

So then you would extract the log from a fit, modify it to your liking and then pass it to transform? That would work for my purposes. Sounds nice

**Comment by jasmainak** [comment]
it's in now :) You should be able to use it
