### ISSUE TITLE
[ENH] Combining Autoreject objects

### ISSUE THREAD

**Issue by eort** [autoreject/autoreject#272]
Hi, 
Would it be possible to combine autoreject objects that we're run on the same data but different channel types, i.e. grads and mags? Like that it would be a little more straightforward to illustrate the data cleaning step in a single plot, and extract these information. Or would this mess with the algorithm?

**Comment by jasmainak** [comment]
currently autoreject does iterate on different channel types if present and for bad epochs, it takes the union of bad epochs detected for each of the channel types. Are you looking for something more than this functionality?

**Comment by jasmainak** [comment]
If [I am reading the code correctly](https://github.com/autoreject/autoreject/blob/9571e1f35497bc5484af8f2cfafcc3c91b6b6f18/autoreject/autoreject.py#L1076-L1083) you should get a single reject log that contains the union of the reject logs of different channel types.

**Comment by eort** [comment]
Yes, thats right. Everything is actually much easier than i thought. Nice :)
