### ISSUE TITLE
Autoreject does not accept 'csd' channel type

### ISSUE THREAD

**Issue by kartavya15** [autoreject/autoreject#275]
Hi there, I computed current source density projections for my epoched EEG data in MNE-Python. This changes the 'eeg' channel types to 'csd' type. Trying autoreject then shows the following error- _ValueError: No channels match the selection.__ Without the CSD step, autoreject works just fine for the same data.

**Comment by jasmainak** [comment]
I think you should apply autoreject on data before CSD. Because CSD will remove spatial correlations which makes the interpolation less accurate. Any thoughts @agramfort ?

**Comment by agramfort** [comment]
Yes I would apply it before CSD 

I don’t know if it’s done to interpolate with spherical harmonics CSD data

**Comment by kartavya15** [comment]
I see. We have a dataset of EEGs with frequent occurrence of high amplitude delta or other high amplitude generalized periodic activity (ICU patients), which is erroneously removed by autoreject (n_interpolate = np.array ([1, 2, 3, 4]), consensus = [0.5]), sometimes rejecting almost half of the epochs! An example of this is in the screeshot below. I can confirm that those are not eyeblinks.

The CSD projections reduce the spread and amplitude of the periodic activity, so I thought may be more permissible for the autoreject amplitude threshold. But, what you have said makes, and CSD is probably not the solution to this problem.

Is autoreject simply not an option for pre-processing for us, when there is high amplitude periodic (but pathological) brain activity throughout the recording?

![Screenshot 2022-06-23 112950](https://user-images.githubusercontent.com/95663154/175349064-83908be9-dbcc-4faf-9294-7fc2d6302d7f.jpg)

**Comment by jasmainak** [comment]
Autoreject cannot distinguish between high amplitude brain activity and high amplitude artifacts. You can increase `consensus` if you want to drop fewer epochs, say to 0.8. Another option is to filter the data to remove high-amplitude brain activity, get the autoreject annotations on the filtered data and apply it on the unfiltered data.

**Comment by kartavya15** [comment]
Thanks, I'll try those out. Appreciate the input.

**Comment by ShahrzadAyoubipour** [comment]
Hi. Can we reset channel types to 'eeg' after CSD, and then apply autoreject?

**Comment by ShahrzadAyoubipour** [comment]
> you can use https://mne.tools/dev/generated/mne.io.Raw.html#mne.io.Raw.set_channel_types
> […](#)
> Message ID: ***@***.***>

Thank you!
After I set channel types to convert channel type from csd to eeg, when I plot my file, there is nothing in my plot. Do you know how can I visualize my file after setting channel types to eeg?
