### ISSUE TITLE
autoreject.compute_thresholds error with no channel locations

### ISSUE THREAD

**Issue by chapochn** [autoreject/autoreject#276]
Hello,
I am trying to use the function `autoreject.compute_thresholds` without channel locations. I set `augment=False`, but still get the error:
`RuntimeError: Valid channel positions are needed for autoreject to work`
Is that to be expected?

**Comment by jasmainak** [comment]
humm ... are you trying to make it work for SEEG? I think the augmentation trick is critical to make autoreject give proper results, specially when there are globally bad channels. But if you want to try anyway, we can fix this error. Feel free to start a pull request!

**Comment by jasmainak** [comment]
What might be probably more impactful if there is an interpolation method that works for sEEG and can be implemented upstream in MNE-Python.

**Comment by chapochn** [comment]
For now, I just did a PR to have `get_rejection_threshold `working. I will also check to update the code for `compute_thresholds`.

Maybe some kind of interpolation could work, only using the closest electrodes, but I'm not sure if I would rely on it...

**Comment by chapochn** [comment]
To make  `compute_thresholds` work, I could just add an optional parameter (true by default) to the function `_check_data`, which tells whether to check or not for location data. Does that sound satisfactory?

**Comment by jasmainak** [comment]
That sounds reasonable to me for now. Interpolation will possibly require source estimation for SEEG and that will take a while to implement in MNE
