### ISSUE TITLE
Possible bug in RANSAC, job distribution calculated wrong

### ISSUE THREAD

**Issue by skjerns** [autoreject/autoreject#277]
While checking the code I stumbled across the following thing. I'm not sure if it's a bug, as I'm not very familiar with RANSAC.

https://github.com/autoreject/autoreject/blob/f1f3536b2f73bee16db3134a312c7fcd2ae25a59/autoreject/ransac.py#L204-L209

Here we get a bunch of random subsets of channels for different jobs. Then we also split up the epochs for different jobs. Then we zip them and run them in parallel.

However, the two variables are of different length. If we e.g. have 29 Epochs and `n_jobs=2`,  `self.ch_subsets_ ` will have 15 entries, whereas `epoch_idxs` has only 2. Therefore the iterator later will only be run two times instead of 15, as `zip` truncates to the shortes iterator parameter. Similarly, if I put `n_jobs=29`, the behaviour reverses, `self_ch_subsets=1` and `epochs_idxs=29`.

I think this is a critical bug, and the random channel subsets should be calculated w.r.t to the number of jobs. ~~However, I don't understand why not each epoch has their own random channel subset, i.e. why this should be dependend on `n_jobs`~~ apparently this is done to get different random seeds in the jobs (#136 ). This might also explain why I'm getting slightly different results for different number of jobs. 

this was introduced in #138

Also `_get_mappings` is running extremely slow (magnitudes longer than the ransac correlation calculations), and the mapping re-calculated for each job, is that intended? Because of this the calculation time is actually increasing when settings `n_jobs>1`

**Comment by agramfort** [comment]
I agree it's weird. The zip is clearly not done over arrays of the same
size.

@jasmainak do you have time  to look?

**Comment by skjerns** [comment]
Additionally, the mappings should probably be only created once for all jobs? I don't fully understand the logic of the mappings though, for different subsets we need different mappings, but why does the number of subsets vary in case we have different jobs?

For `picks=meg`, the function spends 95% of the time creating the mappings.

**Comment by jasmainak** [comment]
I can't quite figure out why it was written the way it was ... this was 5 years ago and Ransac code is hardly touched. If you have ways to fix it, that is most welcome :)
