### ISSUE TITLE
circleci security breach

### ISSUE THREAD

**Issue by sappelhoff** [autoreject/autoreject#296]
may need to follow some steps, see https://github.com/mne-tools/mne-bids/issues/1116

**Comment by sappelhoff** [comment]
@jasmainak @larsoner don't worry if you get emails now about new ssh keys --> that was me, in order to handle the recommendation of rotating the ssh keys.

Should all be done and fine now.

**Comment by jasmainak** [comment]
Thanks a lot @sappelhoff !
