### ISSUE TITLE
CI failing: github_actions_download

### ISSUE THREAD

**Issue by sappelhoff** [autoreject/autoreject#300]
The scheduled CI job is failing at this step: https://github.com/autoreject/autoreject/actions/runs/4154647963/jobs/7187192313#step:10:1

The `github_actions_download` "tool" from MNE-Python seems to be at fault?

https://github.com/mne-tools/mne-python/blob/99bed94f837963bec5bafbca2a1b6a937a2126d3/tools/github_actions_download.sh#L1-L6

Interestingly this fails only on Windows and Mac, but not on Ubuntu. Also this failed just on Python 3.7 but not 3.10.

Upgrading Py versions in https://github.com/autoreject/autoreject/commit/9264d380422a5b1b30d3b5875693ecc7d652d60d did not resolve the issue however (Py 3.7 is soon EoL anyhow, so I dropped it anyhow)

cc @larsoner

**Comment by larsoner** [comment]
Looks like you need to install importlib_resources, or switch to 3.10

**Comment by larsoner** [comment]
(This would get installed automatically if you actually installed the package, but you at that point in the CI run you don't, so you'll have to manually ensure that you have MNE dependencies installed)

**Comment by sappelhoff** [comment]
Thank you @larsoner!
