### ISSUE TITLE
How excluding rejected epochs by Autoreject before ICA do not effect EOG?

### ISSUE THREAD

**Issue by aliosia** [autoreject/autoreject#301]
Hi,
I am working around with AutoReject and ICA for cleaning data. I know that the suggested practice is applying AutoReject before and after ICA and I have checked [this example](https://autoreject.github.io/stable/auto_examples/plot_autoreject_workflow.html#plot-autoreject-workflow).

However, I don’t understand how applying AutoReject before ICA do not badly effect our preprocessing. In fact, Autoreject will find some epochs with EOG artifact as bad epochs. By excluding them from ICA, how should the ICA find the EOG component?

`ica.fit(epochs[~reject_log.bad_epochs])`

Here EOG epochs are among bad_epochs, am I right? and the question is if yes, how ICA can properly understand the EOG component by not seeing them?

You can check the discussion around this question I have asked in MNE discourse [here](https://mne.discourse.group/t/how-excluding-rejected-epochs-by-autoreject-before-ica-do-not-effect-eog/6389).

**Comment by jasmainak** [comment]
closing as answered on discourse !
