### ISSUE TITLE
Issue with picking channels

### ISSUE THREAD

**Issue by paulcbogdan** [autoreject/autoreject#309]
I attempted to use AutoReject while only focusing on a subset of my EEG channels. I specified `picks` as a list of strings, as below. I previously specified that I'm using a BioSemi64 montage for Epochs:
```Python
AR_picks = ['F2', 'Fz', 'F1',
            'FC2', 'FCz', 'FC1',
            'C4', 'C2', 'Cz', 'C1', 'C3',
            'CP4', 'CP2', 'CPz', 'CP1', 'CP3',
            'P4', 'P2', 'Pz', 'P1', 'P3',
            'PO4', 'POz', 'PO3']
ar = AutoReject(verbose=False, picks=AR_picks)
epochs, reject_log = ar.fit_transform(epochs, return_log=True)
```

This yields the following error:

```
  File "....py", line 67, in clean_epochs
    epochs, reject_log = ar.fit_transform(epochs, return_log=True)
  File "....py", line 1188, in fit_transform
    return self.fit(epochs).transform(epochs, return_log=return_log)
  File "...autoreject\autoreject.py", line 1048, in fit
    _run_local_reject_cv(epochs, thresh_func, this_picks,
  File "...autoreject\autoreject.py", line 800, in _run_local_reject_cv
    local_reject.fit(epochs)
  File "..\autoreject\autoreject.py", line 721, in fit
    interp_channels = _get_interp_chs(
  File "...\autoreject\autoreject.py", line 1253, in _get_interp_chs
    np.testing.assert_array_equal(picks, idx_nan_in_row)
  File "...\numpy\testing\_private\utils.py", line 934, in assert_array_equal
    assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
  File "...\numpy\testing\_private\utils.py.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

Mismatched elements: 24 / 24 (100%)
Max absolute difference: 37
Max relative difference: 11.66666667
 x: array([38, 37,  3, 45, 46, 10, 49, 48, 47, 11, 12, 54, 55, 31, 18, 17, 57,
       56, 30, 19, 20, 62, 29, 25])
 y: array([ 3, 10, 11, 12, 17, 18, 19, 20, 25, 29, 30, 31, 37, 38, 45, 46, 47,
       48, 49, 54, 55, 56, 57, 62], dtype=int64)
```

It seems like `x` somewhere is using unsorted channel indices whereas `y` is using sorted channel indices.

I fixed this on my end by going to autoreject.AutoReject.fit and sorting the pick indices from the start:
```Python
def fit(self, epochs):
    self.picks_ = _handle_picks(info=epochs.info, picks=self.picks)
    self.picks_.sort() # My new line
```

I'm not familiar with AutoReject's code, but is this an appropriate solution (or is my problem simply misguided from the start)?

Thanks

**Comment by jasmainak** [comment]
Hi @paulcbogdan I suspect this is because `picks` are not ordered by default in MNE any more (see https://github.com/mne-tools/mne-python/pull/11665). What version of mne-python are you using? cc @larsoner

**Comment by larsoner** [comment]
The behavior change in MNE is that `pick_channels` respects the order of `ch_names` now. So probably in `autoreject` in `_handle_picks` there is a `pick_channels` call that needs to use `ordered=False`, or better (since `ordered=True` does checks for channel name existence for example) is just to `.sort` them afterward as suggested by @paulcbogdan

**Comment by jasmainak** [comment]
thanks @larsoner ! @paulcbogdan do you want to give this a shot with a pull request?

**Comment by paulcbogdan** [comment]
Thanks, I'm on MNE 1.0.3. I should be able to do a pull request later today. 

I also see a `_AutoReject` class. I did not need to change that to fix my issue, but should `.sort` be added there as well?

**Comment by jasmainak** [comment]
you should update/add a test and hopefully that will uncover all the code blocks that need a `sort`

**Comment by paulcbogdan** [comment]
I looked into this, and a `.sort` would not be needed in `_AutoReject` because `_AutoReject` seems to take picks from `AutoReject` after picks were already sorted. 

About a test, do you mean adding something like the code below, which would error under the current package version?

```Python
picks = mne.pick_types(
    epochs.info, meg='mag', eeg=True, stim=False, eog=False,
    include=[], exclude=[])
pick_ch_names = [epochs.ch_names[pp] for pp in picks]
flipped_picks = pick_ch_names[::-1]
ar = AutoReject(cv=3, picks=flipped_picks, random_state=42,
                n_interpolate=[1, 2], consensus=[0.5, 1])
ar.fit(epochs)
```

**Comment by jasmainak** [comment]
yes ... literally something that mimics your bug but in the sample dataset with a couple of lines of code

**Comment by jasmainak** [comment]
any update here @paulcbogdan ?

**Comment by paulcbogdan** [comment]
Sorry, about this delayed response. My understanding of testing and pytest is rather tenuous. I'm guessing that I should just put the code from my previous comment into autoreject/tests/test_autoreject.py, and include that change in a PR? And that's it? I will get to it.

**Comment by sappelhoff** [comment]
- closed in https://github.com/autoreject/autoreject/pull/312
