### ISSUE TITLE
Mismatch between text and code in documentation

### ISSUE THREAD

**Issue by kinleyid** [autoreject/autoreject#318]
Thanks for creating this tool! I plan to use it for an ongoing project. I just ran into the following apparent contradiction in the documentation:

In the example "Preprocessing workflow with autoreject and ICA", the tldr states "We recommend that you first highpass filter the data, then run autoreject (local) and **supply the bad epochs detected by it to the ICA algorithm** for a robust fit, and finally run autoreject (local) again." (emphasis mine). However, in the relevant code, only the _good_ epochs are supplied to the ICA algorithm:
```
# compute ICA
ica = mne.preprocessing.ICA(random_state=99)
ica.fit(epochs[~reject_log.bad_epochs])
```

**Comment by sappelhoff** [comment]
I think this is a language misunderstanding, the idea is to inform the algorithm of the bad epochs (supply the information) so that it only runs on the good epochs. :)

**Comment by jasmainak** [comment]
Actually we have fixed this in the development version of the documentation:

https://autoreject.github.io/dev/auto_examples/plot_autoreject_workflow.html#sphx-glr-auto-examples-plot-autoreject-workflow-py

It should reflect correctly once we cut a release
