### ISSUE TITLE
Example in "Autoreject with highpass filter" not very obvious

### ISSUE THREAD

**Issue by hoechenberger** [autoreject/autoreject#319]
In https://autoreject.github.io/stable/auto_examples/plot_autoreject_workflow.html#autoreject-with-high-pass-filter it says:

> As we can see in the plot, high-pass filtering reduced the number of epochs marked as bad by autoreject substantially.

But the number of bad epochs only dropped from 27 to 23, and I was struggling to see any obvious effect here just by looking at the presented figures.

cc @sappelhoff

**Comment by sappelhoff** [comment]
Let me cc @alexrockhill who has worked on this :) I won't have time to look into this.

**Comment by jasmainak** [comment]
low-frequency drifts can sometimes be captured by peak-to-peak amplitude ... particularly if the epoch occurs when the low-frequency drift starts. That part is obvious to me.

how do you propose to improve the documentation @hoechenberger ?

**Comment by hoechenberger** [comment]
Oh, the the example isn't bad, I just found it confusing that the resulting figure (with and without high-pass filtering) looked basically identical to me, while the text said that I should see some substantial change – which I didn't, so I was lost.

**Comment by alexrockhill** [comment]
I can make a PR to add Mainak's commemt and soften substantial.

**Comment by jasmainak** [comment]
Thanks a lot @alexrockhill !
