### ISSUE TITLE
Disable warning if channels are marked as bad in info["bads"]

### ISSUE THREAD

**Issue by hoechenberger** [autoreject/autoreject#320]
Currently, when running autoreject on data with bad channels in info["bads"], one gets warnings like:

> E   UserWarning: 1 channels are marked as bad. These will be ignored. If you want them to be considered by autoreject please remove them from epochs.info["bads"].

I usually have bads set even if I use autoreject, and these warnings are a bit too verbose for my taste. Would you consider changing the logging level of these messages to "info"? Or provide a switch to turn them off?

**Comment by jasmainak** [comment]
absolutely ... I personally don't have a lot of bandwidth to work on it though. A pull request would be more than welcome!

**Comment by hoechenberger** [comment]
I realized there's a `verbose` parameter in `AutoReject.__init__()`; if set to `False`, it suppresses this warning. This will do for me for now.
