### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by s42255** [autoreject/autoreject#322]
i write this piece of code:
from autoreject import AutoReject
ar = AutoReject()
epochs_clean = ar.fit_transform(epochs)  
and get the error 
AttributeError: module 'mne' has no attribute 'utils'

**Comment by sappelhoff** [comment]
Which version of mne are you running? You can check with `mne.print_sys_info()`. Try upgrading with `pip install -U mne`.

**Comment by agramfort** [comment]
do you have file called mne.py in your folder? if so you should rename it.

**Comment by s42255** [comment]
it worked after i installed it from github and restarted the runtime

**Comment by sappelhoff** [comment]
thanks for letting us know -- have fun with autoreject!
