### ISSUE TITLE
About autoreject==0.3  mne==1.5.1

### ISSUE THREAD

**Issue by moluling** [autoreject/autoreject#336]
because  use tensorflow-gpu==2.6.0,   so numpy ==1.19.5, scipy ==1.7.3,matplotlib==3.3.4,seaborn==0.11.0,   so  mne ==1.5.1,  autoreject==0.3,  but mne and autoreject  is incompatible

**Comment by moluling** [comment]
python ==3.9

**Comment by moluling** [comment]
ImportError: cannot import name 'check_n_jobs' from 'mne.parallel' (G:\Anaconda\envs\tensorflow_gpu\lib\site-packages\mne\parallel.py)

**Comment by sappelhoff** [comment]
I recommend that you dig through the different autoreject releases: https://github.com/autoreject/autoreject/tags

The inspect what version of mne is required for the autoreject release that you are currently looking at.

Once you found a match, install autoreject at exactly that version that you need (if mne MUST be 1.5.1 for you).

**Comment by moluling** [comment]
Official documentation：mne（>=0.24），The comment（# ....） error seems to work, but I hope the official fixes

**Comment by sappelhoff** [comment]
I just checked again, perhaps you could simply upgrade autoreject to its current version? `pip install -U autoreject`

**Comment by moluling** [comment]
My first doc says:{"because use tensorflow-gpu==2.6.0, so numpy ==1.19.5, scipy ==1.7.3,matplotlib==3.3.4,seaborn==0.11.0, so mne ==1.5.1, autoreject==0.3"}.   result：{"ImportError: cannot import name 'check_n_jobs' from 'mne.parallel'“} .    Resolution：（in autoreject.py）Comment out  ” from mne.externals.h5io import read_hbf5. write_hdf5 “.    But I don't want the future or others to be tormented by this.    I hope this version can be fixed, in the future someone will use the framework about （‘tensorflow-gpu’ and 'cuda'） and it make libraries like '( numpy, scipy ,matplotlib)' not upgradeable.     Failed to update （'mne' and ‘autoreject ’） with error .  I hope this issue is a fix and not an update to a new version。 Thank you.

**Comment by jasmainak** [comment]
you shouldn't edit installed files unless you use a development version ... it will create a mess if you try to upgrade your version later. The better fix is to use the latest version as @sappelhoff recommended above
