### ISSUE TITLE
gaussian_process warning message 308

### ISSUE THREAD

**Issue by ramonapariciog** [autoreject/autoreject#35]
Hello everybody!!!
I have a problem, this message appears in each iteration of autoreject during the 'computing thresholds' step:

> /Users/ghfc/anaconda/lib/python3.6/site-packages/sklearn/gaussian_process/gpr.py:308: UserWarning: Predicted variances smaller than 0. Setting those variances to 0.
>   warnings.warn("Predicted variances smaller than 0. "

I'm using the version 0.15.dev0 of mne, and this set of versions:

> numpy                     1.12.1                    <pip>
> scikit-learn              0.18.1              np111py36_1
> scikit-optimize           0.3                       <pip>
> scipy                     0.19.0                    <pip>

I have other environment with other versions, and those messages never appear, and it seems to execute faster:

> mne                         0.14.dev0           <pip>
> numpy                     1.11.1                  py35_0
> scikit-learn              0.18.1              np111py36_1
> scikit-optimize           0.2                       <pip>
> scipy                     0.18.1                    <pip>

I will appreciate a lot If some one has an idea of how to improve this, because compute a file longs about 1 hour with the default settings for the LocalAutorejectCV()

**Comment by jasmainak** [comment]
can you share how many epochs you have in your data?

**Comment by ramonapariciog** [comment]
yeah sure,
i have 953 epochs of 0.8 seconds each one and fs=250 Hz.

**Comment by jasmainak** [comment]
okay you have too many epochs. The sampling frequency doesn't matter much. I can see two solutions:

1. You could run `fit` on a subset of your epochs and then do `transform` on all of them. Something like:

```py
>>> epochs_clean = ar.fit(epochs[::5]).transform(epochs)
```

2. We could also perhaps have a more intelligent way of init. Right now it [takes every fifth peak-to-peak amplitude](https://github.com/autoreject/autoreject/blob/master/autoreject/autoreject.py#L307). It's accurate but probably overkill when there are too many epochs. I'll try to fix it.

Not sure about variance thing. @agramfort any idea if we could suppress `scikit-learn` warnings? Not sure why this is coming up ...

**Comment by agramfort** [comment]
no idea about the warning but I would not ignore it.

can you replicate it?

**Comment by jasmainak** [comment]
well the reason for the warning is the following:

We now initialize the GP based on the peak-to-peak amplitudes. These peak-to-peak amplitudes are very close to each other as you see in the figure below:

![gp_warning](https://cloud.githubusercontent.com/assets/15852194/25489188/5908c808-2b69-11e7-9c50-3e9d83b429ab.png)

Now if you try to `predict` at a point where you already have many points during `fit`, the variance will be close to 0. The `scikit-learn` implementation has numerical issues when the variance is close to 0 - hence the warning.

**Comment by agramfort** [comment]
so maybe you are sampling too many points?

**Comment by jasmainak** [comment]
hmm ... I'm not so sure that's the reason. I could dig in further, but not sure it's worth the effort. For now, I suggest doing what `scikit-optimize` does [here](https://github.com/scikit-optimize/scikit-optimize/blob/e08a067abfa759fa60f279eaf2df569bafc79147/skopt/acquisition.py#L229-L230) : suppress the warnings
