### ISSUE TITLE
ENH: improve performance, try to spot and avoid unnecessary copies during interpolation by relying on picks

### ISSUE THREAD

**Issue by dengemann** [autoreject/autoreject#49]
To be looked into once #45 is in.

**Comment by jasmainak** [comment]
yeah I agree you don't need so many copies during interpolation. Historically, it was just to be safe about things

**Comment by jasmainak** [comment]
can we close this @dengemann ? It seems to me that this was already taken care of in #45

**Comment by jasmainak** [comment]
closing, feel free to reopen @dengemann if you disagree
