### ISSUE TITLE
ENH/API: only one fix_log

### ISSUE THREAD

**Issue by dengemann** [autoreject/autoreject#53]
instead of having bad segments and fix_log, just have one thing.

Expose it with method.

```Python
ar = AutoRejectCV()
ar.fit(epochs)
X_in_sample = ar.annotate(epochs)  # like predict but better name for domain specific purpose
X_new = ar.annotate(other_epochs)

```

Where epochs can be the epochs used in fitting or new data.
The usage and semantics are then easy: Anything that is > than 0 is not good, 1 is bad, 2 is fixed. Document that.

**Comment by jasmainak** [comment]
closed by https://github.com/autoreject/autoreject/pull/97
