### ISSUE TITLE
MAINT: respect sklearn depracations and use modern code

### ISSUE THREAD

**Issue by dengemann** [autoreject/autoreject#65]
- [] cross_validation -> model_selection
- [] KFold API -> n_splits + .get_n_splits(X) + .split(X)

cc @jasmainak

**Comment by jasmainak** [comment]
related https://github.com/autoreject/autoreject/pull/2 but I guess the PR needs to be revamped fresh

**Comment by dengemann** [comment]
> related #2 but I guess the PR needs to be revamped fresh

yeah ...
