### ISSUE TITLE
ENH: consolidate distinction between parameters and attributes in API

### ISSUE THREAD

**Issue by dengemann** [autoreject/autoreject#66]
Currently the API in ARCV, at least, introduces fuzzy loops. If self.cv is None, it will be overwritten in a fit data dependent way. This breaks refitting on differently shaped data as the cv object assumes a certain number of epochs. This and other related issues should be rigorously addressed together with #2 and #65. 

cc @jasmainak

**Comment by jasmainak** [comment]
I think all these issues have been addressed
