### ISSUE TITLE
Store index of remaining epochs in epochs object

### ISSUE THREAD

**Issue by DominiqueMakowski** [autoreject/autoreject#72]
Tracking the index of epochs is useful for doing, for example, cross correlations with behavioral data or so.

For example, to compute epoch-wise signal features and match it with a dataframe with trials (epochs) as rows, one must know the absolute index of each epoch that persists after bad epochs rejection. To be further able to merge data in a nice dataframe:
```
trial     behavioral_scale    signal_feature
0         5.54                     1532.2
1         2.45                     1846.1
2         4.25                     NA
3         1.12                     1132.8
4         8.02                     NA
```

Currently, I did not found if it is the case. However, the indices of remaining epochs can be found as follows:

```python
ar =  autoreject.LocalAutoRejectCV(verbose=False, picks=mne.pick_types(epochs.info, meg=False, eeg=True))
epochs = ar.fit_transform(epochs)
remaining = list(range(len(epochs) + len(ar.bad_epochs_idx)))  # Create a range index
remaining = [x for x in remaining if x not in ar.bad_epochs_idx]  # Remove the bads
```

I can indeed manage to further store this list within the epochs by doing `epochs.info["index"] = remaining`, however, I was wondering if that would be a good idea to store it directly within autoreject functions?

**Comment by dengemann** [comment]
Checkout epochs.selection and epochs.drop_log. We are not going to mess
with epochs.info.

**Comment by DominiqueMakowski** [comment]
...I did not know about epochs.selection... That resolves everything thanks!!
