### ISSUE TITLE
dropping bad epochs with multiple channel types

### ISSUE THREAD

**Issue by jdue** [autoreject/autoreject#73]
I ran autoreject on a dataset containing MEG and EEG channels, however, it failed to transform the epochs due to an `IndexError` at line 636 in `autoreject.py` the reason being that `bad_epochs_idx` was of type float (causing the drop method to fail). Apparently this happens because `np.union1d` returns an array of floats when one of the inputs are an empty list. Possible fix would be changing line 612 to 

    bad_epochs_idx = np.union1d(bad_epochs_idx, bad_epochs_idx_).astype(np.int)

(or setting `dtype` anywhere after this).

**Comment by jasmainak** [comment]
Are you sure this is the right fix? If you do:

```py
In [2]: np.union1d(np.array([1, 3, 4]), np.array([2, 5])).dtype
Out[2]: dtype('int64')
```

Can you share the full traceback? Thanks

**Comment by jdue** [comment]
Yes, but if you do
```
In [147]: np.union1d([], np.array([2, 5])).dtype
Out[147]: dtype('float64')
```
which happens, e.g., when `bad_epochs_idx` is initialized at line 604. The traceback

```
In [143]:  ar.transform(epochs)
[........................................] 100.00000 | Repairing epochs   Traceback (most recent call last):

  File "<ipython-input-143-47d532480cfc>", line 1, in <module>
    ar.transform(epochs)

  File "/mnt/home/jesperdn/git_repos/autoreject/autoreject/autoreject.py", line 914, in transform
    epochs_clean = self.local_reject_.transform(epochs)

  File "/mnt/home/jesperdn/git_repos/autoreject/autoreject/autoreject.py", line 636, in transform
    epochs_out.drop(bad_epochs_idx, reason='AUTOREJECT')

  File "<string>", line 2, in drop

  File "/mnt/home/jesperdn/git_repos/mne-python/mne/utils.py", line 726, in verbose
    return function(*args, **kwargs)

  File "/mnt/home/jesperdn/git_repos/mne-python/mne/epochs.py", line 1058, in drop
    self.drop_log[self.selection[ii]].append(reason)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Comment by jasmainak** [comment]
okay done: https://github.com/autoreject/autoreject/commit/04cae7cee2dc5b423191cac71e84cc94e13524ed

hopefully this fixes your problem :)

**Comment by jdue** [comment]
It did, thanks :)
