### ISSUE TITLE
Typo on autoreject.github.io

### ISSUE THREAD

**Issue by TomDonoghue** [autoreject/autoreject#85]
On the Github pages (and in doc/index.rst, which I'm guessing is where the site pulls from) - there is this code section:
>>> from autoreject import get_rejection_thresholds
>>> reject = get_rejection_thresholds(epochs)

When I try to run it, I can't import get_rejection_thresholds, and when I check the code, it seems simply to be a typo - the function is called get_rejection_threshold, (without the s).

Anyways, just a heads up on that.

**Comment by jasmainak** [comment]
Thanks @TomDonoghue ! This is fixed now in https://github.com/autoreject/autoreject/commit/21697b978d9625d41ff45939c6ab7049d5c45b76
