### ISSUE TITLE
number of epochs rejected -- why one more is rejected?

### ISSUE THREAD

**Issue by antopolskiy** [autoreject/autoreject#87]
I was examining the code to see whether I can model the number of rejected epochs with different consensus values without re-running the algorithm with different consensus values, and I always saw that the number of epochs rejected by autoreject is 1 more than I would reject, using `ar.bad_segments` and consensus value (i.e. `np.where(ar.bad_segments.sum(axis=1)>=(consensus*len(epochs.ch_names)))`, where `ar` is my autoreject model). I believe that the reason is this piece of code in the `autoreject.py`

```
def _get_bad_epochs(self, bad_sensor_counts, ch_type):
    """Get the indices of bad epochs."""
    sorted_epoch_idx = np.argsort(bad_sensor_counts)[::-1]
    bad_sensor_counts = np.sort(bad_sensor_counts)[::-1]
    n_channels = len(self.picks)
    n_consensus = self.consensus_perc[ch_type] * n_channels
    if np.max(bad_sensor_counts) >= n_consensus:
        n_epochs_drop = np.sum(bad_sensor_counts >=
                               n_consensus) + 1
        bad_epochs_idx = sorted_epoch_idx[:n_epochs_drop]
    else:
        n_epochs_drop = 0
        bad_epochs_idx = []
```

What draws my attention is the line `n_epochs_drop = np.sum(bad_sensor_counts >=n_consensus) + 1`, which means that the number of epochs that will be dropped is the number of epochs in which the number of bad channels is higher that the consensus (which is sensible and well described in the paper), **plus one**. So in the end one more epoch is rejected than necessary. Is there a particular reason to do it, or is it a bug?

**Comment by jasmainak** [comment]
looks like a bug to me. Feel free to make a PR.
