### ISSUE TITLE
Bad Channels are Used for Interpolation

### ISSUE THREAD

**Issue by mattboggess** [autoreject/autoreject#92]
Hello,

Thanks for making this tool, it filled a much needed gap in my preprocessing pipeline!

I've run into one issue while using it that I wanted to raise though. If the epochs object that you run autoreject on has bad channels marked, these get ignored when running autoreject as expected. However, when actually transforming the original epochs to get the cleaned version, these bad channels are used to interpolate the bad channels that autoreject marked, often resulting in less clean data than before.

This appears to be due to the fact that the bad channels during the interpolation process are reset to the ones determined by autoreject, overwriting the previously marked bad channels. By instead appending the autoreject bad channels this behavior can be avoided with the one side effect that the other bad channels not marked by autoreject will get interpolated as well. In the code.

In the code, this amounts to changing the = in line 677 of autoreject.py to a +=. I'd be happy to submit a pull request to fix this.

I realize that the intention of the design was to allow autoreject to do the job of detecting bad channels itself. However, I am unfortunately working with quite noisy data and I find that marking bad channels and running ICA ahead allows autoreject to clean up the remaining data and works quite well. If I just run autoreject directly, it throws out most of my data. This fix would allow this use case.

Thanks!

**Comment by jasmainak** [comment]
Hi @mattboggess this does sound like a bugfix. Could you make a PR and add a test? Thanks

**Comment by jasmainak** [comment]
closed by https://github.com/autoreject/autoreject/pull/93
